import {
  Activity,
  FileText,
  Gauge,
  Globe,
  Network,
  Radar,
  Route as RouteIcon,
  Shield,
  ShieldCheck,
  Workflow,
  Zap,
} from "lucide-react";
import type { AltLandingConfig } from "@/components/alt-landing";

/**
 * Content for the SEO "alternative / client" landing pages. Each key maps to
 * a route pair: /<slug> (zh) and /en/<slug> (en).
 */
export type LandingPageDef = {
  zh: { head: HeadMeta; cfg: AltLandingConfig };
  en: { head: HeadMeta; cfg: AltLandingConfig };
};

type HeadMeta = { title: string; desc: string; ogTitle: string; ogDesc: string; crumb: string };

export const LANDING_PAGES: Record<string, LandingPageDef> = {
  "qv2ray-alternative": {
    zh: {
      head: {
        title: "AirLane — Qv2ray 替代方案 | 仍在维护的现代代理客户端",
        desc: "Qv2ray 已停止维护多年，协议停留在 VMess/VLESS 旧时代。AirLane 是活跃迭代的现代替代：sing-box 内核 38+ 协议（Hysteria2/TUIC/Reality），跨平台可视化策略树、流量仪表盘、健康自愈与 Mesh 组网。",
        ogTitle: "AirLane — Qv2ray 替代方案",
        ogDesc: "Qv2ray 已停更——换到活跃维护的 sing-box 可视化客户端，38+ 协议全平台。",
        crumb: "Qv2ray 替代",
      },
      cfg: {
        badge: "Qv2ray 替代方案",
        titlePre: "Qv2ray 停更了，",
        titleEm: "下一站 AirLane",
        sub: "Qv2ray 项目早已停止维护，新协议（Hysteria2、TUIC、Reality）一概没有。AirLane 是活跃开发的现代化替代：sing-box 内核、38+ 协议、可视化策略树与跨设备 Mesh——延续 Qv2ray 的插件式理念，做成产品。",
        featuresTitle: "从 Qv2ray 迁移到 AirLane",
        featuresSub: "当年选 Qv2ray 是因为要可扩展的客户端——AirLane 把这条路走完了。",
        features: [
          { icon: Zap, title: "38+ 新协议", desc: "Qv2ray 停在 VMess/VLESS/Trojan 时代；AirLane 原生支持 Hysteria2、TUIC v5、Reality、ShadowTLS、WireGuard。" },
          { icon: Globe, title: "全平台统一", desc: "Qv2ray 只有桌面三件套；AirLane Windows/macOS/Linux/Android/iOS 同一内核同一 UI。" },
          { icon: Workflow, title: "策略树编排", desc: "Qv2ray 的路由编辑器平铺规则；AirLane 用可嵌套策略树表达复杂分流。" },
          { icon: Activity, title: "内置仪表盘", desc: "实时吞吐、连接明细、按出口聚合——Qv2ray 时代要靠日志和外部工具。" },
          { icon: Gauge, title: "健康自愈", desc: "节点异常自动切换并留痕；Qv2ray 只能手动 ping 再手选。" },
          { icon: Network, title: "Mesh 资源池", desc: "设备间共享出口，Qv2ray 架构里没有的概念。" },
        ],
        compareTitle: "AirLane vs Qv2ray 全面对比",
        rivalName: "Qv2ray",
        comparison: [
          { capability: "维护状态", rival: "已停更（2021）", airlane: "活跃开发中" },
          { capability: "内核", rival: "v2ray 内核", airlane: "sing-box 内核" },
          { capability: "新协议", rival: "无 Hy2/TUIC/Reality", airlane: "38+ 协议原生支持" },
          { capability: "平台", rival: "Win/macOS/Linux", airlane: "桌面 + Android + iOS" },
          { capability: "路由", rival: "规则编辑器", airlane: "可嵌套策略树" },
          { capability: "观测性", rival: "连接列表", airlane: "仪表盘 + 决策追踪" },
          { capability: "多端协同", rival: "无", airlane: "Mesh 共享出口池" },
        ],
        ctaTitle: "离开停更项目，不丢任何节点",
        ctaDesc: "v2ray 订阅和 URI 列表直接导入，历史节点一个不落。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "AirLane — Qv2ray Alternative | An Actively Maintained Proxy Client",
        desc: "Qv2ray has been unmaintained for years — stuck at VMess-era protocols. AirLane is the actively developed modern alternative: sing-box core, 38+ protocols (Hysteria2/TUIC/Reality), cross-platform policy trees, traffic dashboard, self-healing and Mesh networking.",
        ogTitle: "AirLane — Qv2ray Alternative",
        ogDesc: "Qv2ray is unmaintained — switch to an actively developed visual sing-box client, 38+ protocols.",
        crumb: "Qv2ray Alternative",
      },
      cfg: {
        badge: "Qv2ray Alternative",
        titlePre: "Qv2ray is unmaintained —",
        titleEm: "meet AirLane",
        sub: "The Qv2ray project stopped years ago; it never learned Hysteria2, TUIC or Reality. AirLane is the actively developed modern successor: sing-box core, 38+ protocols, visual policy trees and cross-device Mesh — the plugin-era idea, finished as a product.",
        featuresTitle: "Migrating from Qv2ray to AirLane",
        featuresSub: "You chose Qv2ray for an extensible client — AirLane completed that vision.",
        features: [
          { icon: Zap, title: "38+ modern protocols", desc: "Qv2ray froze at VMess/VLESS/Trojan; AirLane natively supports Hysteria2, TUIC v5, Reality, ShadowTLS and WireGuard." },
          { icon: Globe, title: "One client everywhere", desc: "Qv2ray was desktop-only; AirLane runs the same core and UI on Windows, macOS, Linux, Android and iOS." },
          { icon: Workflow, title: "Policy-tree orchestration", desc: "Qv2ray's flat rule editor becomes AirLane's nestable policy tree for complex splitting." },
          { icon: Activity, title: "Built-in dashboard", desc: "Live throughput, connection detail, per-exit traffic — things Qv2ray needed external tools for." },
          { icon: Gauge, title: "Self-healing exits", desc: "Unhealthy nodes fail over automatically with an audit trail; Qv2ray needed manual ping-and-pick." },
          { icon: Network, title: "Mesh resource pools", desc: "Share exits across devices — a concept Qv2ray never had." },
        ],
        compareTitle: "AirLane vs Qv2ray — Full Comparison",
        rivalName: "Qv2ray",
        comparison: [
          { capability: "Maintenance", rival: "Unmaintained (2021)", airlane: "Actively developed" },
          { capability: "Core", rival: "v2ray core", airlane: "sing-box core" },
          { capability: "New protocols", rival: "No Hy2/TUIC/Reality", airlane: "38+ native protocols" },
          { capability: "Platforms", rival: "Win/macOS/Linux", airlane: "Desktop + Android + iOS" },
          { capability: "Routing", rival: "Rule editor", airlane: "Nestable policy tree" },
          { capability: "Observability", rival: "Connection list", airlane: "Dashboard + decision tracing" },
          { capability: "Multi-device", rival: "None", airlane: "Mesh shared pools" },
        ],
        ctaTitle: "Leave an unmaintained client, keep every node",
        ctaDesc: "v2ray subscriptions and URI lists import directly — nothing gets left behind.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },

  "sing-box-gui": {
    zh: {
      head: {
        title: "AirLane — 最好用的 Sing-box GUI | 可视化 Sing-box 桌面客户端",
        desc: "AirLane 是基于 sing-box 内核的可视化 GUI 客户端（Sing-box GUI / Dashboard / Manager）：告别手写 JSON 配置，可视化节点管理、策略树路由、流量面板、健康检测与 Mesh 组网。支持 VLESS、Hysteria2、TUIC、Reality 等 38+ 协议，Windows/macOS/Linux/Android/iOS 全平台。",
        ogTitle: "AirLane — 最好用的 Sing-box GUI",
        ogDesc: "可视化 sing-box 客户端：节点管理、策略树、流量仪表盘、健康检测，告别 JSON 配置。",
        crumb: "Sing-box GUI",
      },
      cfg: {
        badge: "Sing-box GUI",
        titlePre: "最好用的",
        titleEm: "Sing-box GUI",
        sub: "sing-box 内核能力极强，但 JSON 配置劝退大多数人。AirLane 给它装上了产品级图形界面：可视化节点管理、可嵌套策略树、实时流量仪表盘、节点健康评分——Sing-box Manager 该有的样子。",
        featuresTitle: "为什么 AirLane 是最好的 Sing-box GUI？",
        featuresSub: "sing-box 内核的全部能力，可视化交付，零 JSON。",
        features: [
          { icon: Workflow, title: "可视化策略树", desc: "把 sing-box 的 route.rules / outbounds 抽象为可嵌套策略树，拖拽编排分流逻辑，不写一行 JSON。" },
          { icon: Activity, title: "流量仪表盘", desc: "实时吞吐、连接数、按出口聚合的流量视图——Sing-box Dashboard 级别的可观测性内置其中。" },
          { icon: Gauge, title: "节点健康评分", desc: "延迟、抖动、丢包三维评分，自动切换故障节点并记录自愈原因。" },
          { icon: FileText, title: "订阅一键导入", desc: "Clash / Mihomo / sing-box 订阅链接与 URI 列表自动识别，生成结构化节点库。" },
          { icon: Shield, title: "泄漏检测", desc: "内置 DNS / WebRTC / IPv6 泄漏测试，连接前验证隐私面。" },
          { icon: Network, title: "Mesh 组网", desc: "跨设备共享出口与资源池，桌面与移动端共用同一控制面。" },
        ],
        compareTitle: "手写 JSON vs AirLane",
        rivalName: "原生 sing-box",
        comparison: [
          { capability: "配置方式", rival: "手写 JSON config", airlane: "可视化对象模型" },
          { capability: "路由规则", rival: "route.rules 数组", airlane: "可嵌套策略树" },
          { capability: "节点选择", rival: "修改 outbound default", airlane: "点选 + 自动优选" },
          { capability: "流量监控", rival: "第三方面板", airlane: "内置仪表盘" },
          { capability: "健康检测", rival: "无", airlane: "评分 + 自愈" },
          { capability: "订阅导入", rival: "手动转换", airlane: "一键导入 + 迁移报告" },
          { capability: "多端同步", rival: "各自维护配置", airlane: "Mesh 共享出口池" },
        ],
        ctaTitle: "把 sing-box 用起来，而不是配起来",
        ctaDesc: "下载 AirLane，导入订阅，点选出口——3 分钟完成别人半小时的 JSON 调试。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "AirLane — Best Sing-box GUI | Visual Sing-box Client & Dashboard",
        desc: "AirLane is the visual GUI for the sing-box core: node manager, policy tree routing, traffic dashboard, health scoring and Mesh networking — no JSON. VLESS, Hysteria2, TUIC, Reality and 38+ protocols on Windows, macOS, Linux, Android and iOS.",
        ogTitle: "AirLane — Best Sing-box GUI",
        ogDesc: "Visual sing-box client: node manager, policy tree, traffic dashboard, health checks — no JSON.",
        crumb: "Sing-box GUI",
      },
      cfg: {
        badge: "Sing-box GUI",
        titlePre: "The",
        titleEm: "Sing-box GUI",
        sub: "The sing-box core is incredibly capable — but its JSON config scares most people away. AirLane gives it a product-grade UI: visual node management, nestable policy trees, a live traffic dashboard and node health scoring. What a Sing-box Manager should be.",
        featuresTitle: "Why AirLane is the best Sing-box GUI",
        featuresSub: "All of sing-box's power, delivered visually — zero JSON.",
        features: [
          { icon: Workflow, title: "Visual policy tree", desc: "sing-box route.rules and outbounds become a nestable policy tree — drag to orchestrate traffic, no JSON written." },
          { icon: Activity, title: "Traffic dashboard", desc: "Live throughput, connection counts, per-exit traffic aggregation — Sing-box Dashboard-grade observability built in." },
          { icon: Gauge, title: "Node health scoring", desc: "Latency, jitter and packet-loss scoring with automatic failover and self-healing history." },
          { icon: FileText, title: "One-click subscription import", desc: "Clash / Mihomo / sing-box subscription links and URI lists auto-detected into a structured node library." },
          { icon: Shield, title: "Leak detection", desc: "Built-in DNS / WebRTC / IPv6 leak tests verify your privacy surface before you connect." },
          { icon: Network, title: "Mesh networking", desc: "Share exits and resource pools across devices — desktop and mobile on one control plane." },
        ],
        compareTitle: "Hand-written JSON vs AirLane",
        rivalName: "Stock sing-box",
        comparison: [
          { capability: "Configuration", rival: "Hand-written JSON", airlane: "Visual object model" },
          { capability: "Routing rules", rival: "route.rules arrays", airlane: "Nestable policy tree" },
          { capability: "Node selection", rival: "Edit outbound default", airlane: "Click + auto-select" },
          { capability: "Traffic monitoring", rival: "Third-party panels", airlane: "Built-in dashboard" },
          { capability: "Health checks", rival: "None", airlane: "Scoring + self-healing" },
          { capability: "Subscription import", rival: "Manual conversion", airlane: "One-click + migration report" },
          { capability: "Multi-device sync", rival: "Per-device configs", airlane: "Mesh shared exit pool" },
        ],
        ctaTitle: "Use sing-box, don't configure it",
        ctaDesc: "Download AirLane, import a subscription, pick an exit — three minutes instead of half an hour of JSON debugging.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },

  "v2rayn-alternative": {
    zh: {
      head: {
        title: "AirLane — 现代化的 V2RayN 替代方案 | 跨平台代理客户端",
        desc: "AirLane 是 V2RayN / v2rayNG 的现代替代：不止 Windows，macOS/Linux/Android/iOS 全平台一致的 sing-box 内核客户端。可视化策略树替代路由规则 JSON，38+ 协议支持，内置流量仪表盘与 Mesh 组网。",
        ogTitle: "AirLane — 现代化的 V2RayN 替代方案",
        ogDesc: "不再只有 Windows：sing-box 内核全平台可视化代理客户端，38+ 协议。",
        crumb: "V2RayN 替代",
      },
      cfg: {
        badge: "V2RayN 替代方案",
        titlePre: "现代化的",
        titleEm: "V2RayN 替代",
        sub: "V2RayN 是 Windows 上的经典，但界面停留在上个时代，多平台体验割裂。AirLane 用 sing-box 内核 + 产品级 UI 重做这件事：Windows、macOS、Linux、Android、iOS 同一套交互，38+ 协议全支持。",
        featuresTitle: "从 V2RayN 切换到 AirLane 的理由",
        featuresSub: "同样的节点，更现代的体验、更广的协议、更少的折腾。",
        features: [
          { icon: Globe, title: "真正的全平台", desc: "Windows / macOS / Linux / Android / iOS 同一内核同一 UI，配置和订阅跨设备同步。" },
          { icon: Zap, title: "38+ 协议", desc: "VLESS、VMess、Trojan、Hysteria2、TUIC v5、Reality、WireGuard 等原生支持，覆盖比 v2ray 内核更广。" },
          { icon: Workflow, title: "可视化分流", desc: "域名/IP/进程三维规则可视化编排，替代 V2RayN 的路由规则 JSON 编辑。" },
          { icon: Activity, title: "流量与延迟面板", desc: "实时吞吐、节点延迟、连接明细一目了然，不用翻日志猜状态。" },
          { icon: ShieldCheck, title: "泄漏检测内置", desc: "DNS/WebRTC/IPv6 泄漏一键检测，防止代理已连但真实出口暴露。" },
          { icon: Network, title: "Mesh 共享出口", desc: "多设备间共享节点资源池，手机也能走电脑的优质线路。" },
        ],
        compareTitle: "AirLane vs V2RayN 全面对比",
        rivalName: "V2RayN",
        comparison: [
          { capability: "内核", rival: "v2ray/Xray 内核", airlane: "sing-box 内核" },
          { capability: "平台", rival: "仅 Windows", airlane: "Win/macOS/Linux/Android/iOS" },
          { capability: "协议", rival: "VMess/VLESS/SS/Trojan", airlane: "38+ 含 Hysteria2/TUIC" },
          { capability: "路由配置", rival: "JSON 规则编辑", airlane: "可视化策略树" },
          { capability: "订阅", rival: "v2ray 订阅", airlane: "Clash/Mihomo/sing-box/URI 全兼容" },
          { capability: "流量观测", rival: "基础统计", airlane: "实时仪表盘 + 连接明细" },
          { capability: "多端协同", rival: "无", airlane: "Mesh 组网共享出口" },
        ],
        ctaTitle: "换客户端不用换订阅",
        ctaDesc: "导入现有订阅链接即可迁移，节点自动归类、策略自动生成。",
        ctaLabel: "查看迁移指南",
        ctaTo: "/migration",
      },
    },
    en: {
      head: {
        title: "AirLane — A Modern V2RayN Alternative | Cross-Platform Proxy Client",
        desc: "AirLane is the modern alternative to V2RayN / v2rayNG: one sing-box-core client across Windows, macOS, Linux, Android and iOS. Visual policy trees replace JSON routing rules, 38+ protocols, built-in traffic dashboard and Mesh networking.",
        ogTitle: "AirLane — A Modern V2RayN Alternative",
        ogDesc: "Not Windows-only anymore: visual sing-box client on every platform, 38+ protocols.",
        crumb: "V2RayN Alternative",
      },
      cfg: {
        badge: "V2RayN Alternative",
        titlePre: "A Modern",
        titleEm: "V2RayN Alternative",
        sub: "V2RayN is a Windows classic, but its UI is from another era and every other platform gets a different app. AirLane redoes it with the sing-box core and a product-grade UI — one interaction model on Windows, macOS, Linux, Android and iOS, 38+ protocols.",
        featuresTitle: "Why switch from V2RayN to AirLane",
        featuresSub: "Same nodes — modern UX, wider protocol coverage, less fiddling.",
        features: [
          { icon: Globe, title: "Truly cross-platform", desc: "One core and one UI on Windows, macOS, Linux, Android and iOS — configs and subscriptions sync across devices." },
          { icon: Zap, title: "38+ protocols", desc: "Native VLESS, VMess, Trojan, Hysteria2, TUIC v5, Reality, WireGuard and more — wider than the v2ray core." },
          { icon: Workflow, title: "Visual traffic splitting", desc: "Domain/IP/process rules composed visually — replaces V2RayN's JSON routing editor." },
          { icon: Activity, title: "Traffic & latency panels", desc: "Live throughput, per-node latency and connection detail at a glance — no log digging." },
          { icon: ShieldCheck, title: "Built-in leak tests", desc: "One-click DNS/WebRTC/IPv6 leak detection so a connected proxy never leaks your real exit." },
          { icon: Network, title: "Mesh shared exits", desc: "Share node resource pools across devices — your phone can ride your desktop's best route." },
        ],
        compareTitle: "AirLane vs V2RayN — Full Comparison",
        rivalName: "V2RayN",
        comparison: [
          { capability: "Core", rival: "v2ray/Xray core", airlane: "sing-box core" },
          { capability: "Platforms", rival: "Windows only", airlane: "Win/macOS/Linux/Android/iOS" },
          { capability: "Protocols", rival: "VMess/VLESS/SS/Trojan", airlane: "38+ incl. Hysteria2/TUIC" },
          { capability: "Routing config", rival: "JSON rule editing", airlane: "Visual policy tree" },
          { capability: "Subscriptions", rival: "v2ray format", airlane: "Clash/Mihomo/sing-box/URI" },
          { capability: "Observability", rival: "Basic stats", airlane: "Live dashboard + connections" },
          { capability: "Multi-device", rival: "None", airlane: "Mesh shared exits" },
        ],
        ctaTitle: "Switch clients, keep your subscriptions",
        ctaDesc: "Import your existing subscription links — nodes auto-classified, policies auto-generated.",
        ctaLabel: "Migration Guide",
        ctaTo: "/en/migration",
      },
    },
  },

  "nekobox-alternative": {
    zh: {
      head: {
        title: "AirLane — NekoBox / NekoRay 替代方案 | 全平台 sing-box 客户端",
        desc: "AirLane 是 NekoBox / NekoRay / NekoBox for Android 的现代替代：同为 sing-box 内核，但提供产品级可视化界面——策略树、流量仪表盘、健康评分、Mesh 组网，桌面与移动端体验统一。",
        ogTitle: "AirLane — NekoBox 替代方案",
        ogDesc: "同内核，更产品化：NekoBox 的现代替代，桌面+移动端统一体验。",
        crumb: "NekoBox 替代",
      },
      cfg: {
        badge: "NekoBox 替代方案",
        titlePre: "NekoBox 的",
        titleEm: "现代替代",
        sub: "NekoBox / NekoRay 同为 sing-box 内核，能力全面但 UI 偏工程师工具。AirLane 在同内核之上提供产品级体验：可视化策略树、实时仪表盘、健康自愈、跨设备 Mesh——桌面和 Android 体验完全一致。",
        featuresTitle: "AirLane 比 NekoBox 多做了什么",
        featuresSub: "同内核，补齐的是产品化体验和可观测性。",
        features: [
          { icon: Workflow, title: "策略树而非规则列表", desc: "NekoBox 的路由配置是平铺规则，AirLane 把它抽象为可嵌套策略树，复杂分流一眼看懂。" },
          { icon: Activity, title: "真正的仪表盘", desc: "吞吐曲线、连接明细、出口聚合流量——NekoBox 需要靠日志推断的东西全部可视化。" },
          { icon: Gauge, title: "健康评分与自愈", desc: "节点异常自动切换并留痕，比手动 URL 测速更进一步。" },
          { icon: Network, title: "跨设备 Mesh", desc: "NekoBox 各端独立；AirLane 让桌面与手机共享出口池与资源。" },
          { icon: FileText, title: "订阅格式全兼容", desc: "Clash/Mihomo/sing-box/URI 列表直接导入，NekoBox 订阅无需转换。" },
          { icon: Radar, title: "决策追踪", desc: "输入域名看完整决策链 DNS→规则→策略→出口，排错不再猜。" },
        ],
        compareTitle: "AirLane vs NekoBox 全面对比",
        rivalName: "NekoBox / NekoRay",
        comparison: [
          { capability: "内核", rival: "sing-box", airlane: "sing-box（同内核）" },
          { capability: "界面定位", rival: "工程师工具", airlane: "产品级 GUI" },
          { capability: "路由编排", rival: "平铺规则列表", airlane: "可嵌套策略树" },
          { capability: "流量面板", rival: "基础", airlane: "实时仪表盘" },
          { capability: "健康检测", rival: "URL 测速", airlane: "评分 + 自动自愈" },
          { capability: "跨设备", rival: "各端独立", airlane: "Mesh 组网共享" },
          { capability: "泄漏检测", rival: "无", airlane: "内置一键检测" },
        ],
        ctaTitle: "同内核，换更好的壳",
        ctaDesc: "订阅与节点无缝导入，切换零成本——下载即用。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "AirLane — NekoBox / NekoRay Alternative | Sing-box Client for All Platforms",
        desc: "AirLane is the modern alternative to NekoBox / NekoRay / NekoBox for Android: same sing-box core, but a product-grade UI — policy trees, traffic dashboard, health scoring and cross-device Mesh, with identical desktop and mobile UX.",
        ogTitle: "AirLane — NekoBox Alternative",
        ogDesc: "Same core, product-grade UX: the modern NekoBox alternative on desktop and mobile.",
        crumb: "NekoBox Alternative",
      },
      cfg: {
        badge: "NekoBox Alternative",
        titlePre: "The Modern",
        titleEm: "NekoBox Alternative",
        sub: "NekoBox / NekoRay runs on the same sing-box core — capable but engineer-oriented. AirLane adds the product layer: visual policy trees, a live dashboard, health self-healing and cross-device Mesh, with identical UX on desktop and Android.",
        featuresTitle: "What AirLane adds over NekoBox",
        featuresSub: "Same core — the difference is productization and observability.",
        features: [
          { icon: Workflow, title: "Policy tree, not rule lists", desc: "NekoBox's routing is a flat rule list; AirLane models it as a nestable policy tree you can actually read." },
          { icon: Activity, title: "A real dashboard", desc: "Throughput curves, connection detail, per-exit traffic — everything NekoBox hides in logs is visualized." },
          { icon: Gauge, title: "Health scoring & self-healing", desc: "Automatic failover with an audit trail — a step beyond manual URL testing." },
          { icon: Network, title: "Cross-device Mesh", desc: "NekoBox devices work alone; AirLane shares exit pools and resources between desktop and phone." },
          { icon: FileText, title: "Universal subscription import", desc: "Clash/Mihomo/sing-box/URI lists import directly — NekoBox subscriptions need no conversion." },
          { icon: Radar, title: "Decision tracing", desc: "Type a domain, see the full chain DNS → rule → policy → exit. No more guessing." },
        ],
        compareTitle: "AirLane vs NekoBox — Full Comparison",
        rivalName: "NekoBox / NekoRay",
        comparison: [
          { capability: "Core", rival: "sing-box", airlane: "sing-box (same core)" },
          { capability: "UX positioning", rival: "Engineer's tool", airlane: "Product-grade GUI" },
          { capability: "Routing", rival: "Flat rule lists", airlane: "Nestable policy tree" },
          { capability: "Traffic panel", rival: "Basic", airlane: "Live dashboard" },
          { capability: "Health checks", rival: "URL test", airlane: "Scoring + self-healing" },
          { capability: "Multi-device", rival: "Standalone", airlane: "Mesh shared pools" },
          { capability: "Leak tests", rival: "None", airlane: "Built-in one-click" },
        ],
        ctaTitle: "Same core, better shell",
        ctaDesc: "Subscriptions and nodes import seamlessly — switching costs nothing.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },

  "hiddify-alternative": {
    zh: {
      head: {
        title: "AirLane — Hiddify 替代方案 | 更深度的可视化代理客户端",
        desc: "AirLane 是 Hiddify / Hiddify Next 的替代方案：sing-box 内核全平台客户端，但走得更远——可嵌套策略树、逐连接决策追踪、节点健康评分、Mesh 组网与出口资源池，不只是简单的一键连接。",
        ogTitle: "AirLane — Hiddify 替代方案",
        ogDesc: "不止一键连接：策略树、决策追踪、健康自愈、Mesh 组网的深度客户端。",
        crumb: "Hiddify 替代",
      },
      cfg: {
        badge: "Hiddify 替代方案",
        titlePre: "比 Hiddify",
        titleEm: "更深一层",
        sub: "Hiddify 胜在简单，但当你需要看清流量去向、编排复杂分流、管理多出口资源时它就到头了。AirLane 面向想要可控性的用户：策略树、决策追踪、健康自愈、Mesh 资源池——简单之上，更有深度。",
        featuresTitle: "什么时候该从 Hiddify 换到 AirLane",
        featuresSub: "一键连接满足入门，但这些场景需要更强的控制面。",
        features: [
          { icon: RouteIcon, title: "复杂分流编排", desc: "按域名/IP/进程/端口嵌套组合策略，Hiddify 的分流只是单层规则。" },
          { icon: Radar, title: "决策追踪", desc: "每条连接的 DNS→规则→策略→出口链路全程可回放，Hiddify 只有开关。" },
          { icon: Activity, title: "流量仪表盘", desc: "按出口/应用聚合的实时流量视图，知道每个 GB 花在哪。" },
          { icon: Network, title: "Mesh 资源池", desc: "多设备共享节点与出口，团队/家庭共用一份资源——Hiddify 不具备。" },
          { icon: Gauge, title: "健康评分自愈", desc: "节点劣化自动切换并记录原因，而非静默失败。" },
          { icon: Zap, title: "38+ 协议", desc: "VLESS/VMess/Trojan/Hysteria2/TUIC/Reality/WireGuard 等原生全支持。" },
        ],
        compareTitle: "AirLane vs Hiddify 全面对比",
        rivalName: "Hiddify",
        comparison: [
          { capability: "内核", rival: "sing-box", airlane: "sing-box（同内核）" },
          { capability: "定位", rival: "极简一键连接", airlane: "可视化控制面" },
          { capability: "分流", rival: "基础规则", airlane: "可嵌套策略树" },
          { capability: "观测性", rival: "连接状态", airlane: "决策追踪 + 仪表盘" },
          { capability: "自愈", rival: "手动切换", airlane: "评分驱动自动切换" },
          { capability: "多设备", rival: "各端独立", airlane: "Mesh 共享出口池" },
          { capability: "订阅兼容", rival: "主流格式", airlane: "Clash/Mihomo/sing-box 全兼容" },
        ],
        ctaTitle: "从一键连接到完整控制面",
        ctaDesc: "导入 Hiddify 同款订阅，立即获得可视化策略编排与观测能力。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "AirLane — Hiddify Alternative | Deeper Visual Proxy Client",
        desc: "AirLane is the alternative to Hiddify / Hiddify Next: a sing-box-core client on all platforms that goes further — nestable policy trees, per-connection decision tracing, node health scoring, Mesh networking and shared exit pools, beyond one-tap connect.",
        ogTitle: "AirLane — Hiddify Alternative",
        ogDesc: "Beyond one-tap: policy trees, decision tracing, self-healing and Mesh resource pools.",
        crumb: "Hiddify Alternative",
      },
      cfg: {
        badge: "Hiddify Alternative",
        titlePre: "One Layer",
        titleEm: "Deeper Than Hiddify",
        sub: "Hiddify wins on simplicity — but it ends where real traffic control begins. AirLane is for users who want to see where traffic goes, compose complex splitting and manage multi-exit resources: policy trees, decision tracing, self-healing, Mesh pools.",
        featuresTitle: "When to move from Hiddify to AirLane",
        featuresSub: "One-tap connect covers the basics — these scenarios need a control plane.",
        features: [
          { icon: RouteIcon, title: "Complex split routing", desc: "Nest rules by domain/IP/process/port — Hiddify's splitting is single-layer." },
          { icon: Radar, title: "Decision tracing", desc: "Every connection's DNS → rule → policy → exit chain is replayable; Hiddify only shows on/off." },
          { icon: Activity, title: "Traffic dashboard", desc: "Real-time traffic aggregated by exit and app — know where every GB went." },
          { icon: Network, title: "Mesh resource pools", desc: "Share nodes and exits across devices — a team or family on one pool. Hiddify can't." },
          { icon: Gauge, title: "Scored self-healing", desc: "Degraded nodes switch automatically with a recorded reason, not silent failure." },
          { icon: Zap, title: "38+ protocols", desc: "Native VLESS/VMess/Trojan/Hysteria2/TUIC/Reality/WireGuard and more." },
        ],
        compareTitle: "AirLane vs Hiddify — Full Comparison",
        rivalName: "Hiddify",
        comparison: [
          { capability: "Core", rival: "sing-box", airlane: "sing-box (same core)" },
          { capability: "Positioning", rival: "Minimal one-tap", airlane: "Visual control plane" },
          { capability: "Splitting", rival: "Basic rules", airlane: "Nestable policy tree" },
          { capability: "Observability", rival: "Connection state", airlane: "Decision tracing + dashboard" },
          { capability: "Self-healing", rival: "Manual switching", airlane: "Score-driven failover" },
          { capability: "Multi-device", rival: "Standalone", airlane: "Mesh shared pools" },
          { capability: "Subscriptions", rival: "Mainstream formats", airlane: "Clash/Mihomo/sing-box all" },
        ],
        ctaTitle: "From one-tap to full control",
        ctaDesc: "Import the same subscription you use in Hiddify — instantly get visual policy orchestration and observability.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },

  "hysteria2-client": {
    zh: {
      head: {
        title: "AirLane — Hysteria2 可视化客户端 | Hysteria2 GUI 桌面客户端",
        desc: "AirLane 是开箱即用的 Hysteria2 GUI 客户端：粘贴 hysteria2:// 分享链接即导入，自动处理自签证书 insecure 参数，延迟测速、自动切换、流量统计全可视化。Windows/macOS/Linux/Android/iOS 全平台，同时支持 TUIC、VLESS Reality 等 38+ 协议。",
        ogTitle: "AirLane — Hysteria2 可视化客户端",
        ogDesc: "hysteria2:// 链接一键导入，自签证书自动处理，测速与切换全可视化。",
        crumb: "Hysteria2 客户端",
      },
      cfg: {
        badge: "Hysteria2 GUI 客户端",
        titlePre: "开箱即用的",
        titleEm: "Hysteria2 客户端",
        sub: "Hysteria2 基于 QUIC，烂线路上跑满带宽——但官方只有命令行。AirLane 把它变成图形客户端：粘贴 hysteria2:// 链接即导入，insecure 自签证书自动处理，测速、分流、自动切换全部可视化。",
        featuresTitle: "AirLane 的 Hysteria2 体验",
        featuresSub: "hy2 协议的全部性能，GUI 的全部便利。",
        features: [
          { icon: Zap, title: "链接即导入", desc: "直接粘贴 hysteria2:// / hy2:// 分享链接或订阅，端口、密码、SNI 自动解析入库。" },
          { icon: ShieldCheck, title: "自签证书自动处理", desc: "裸 IP 节点的 insecure=1 自动识别，不再手动跳过证书校验报错。" },
          { icon: Gauge, title: "QUIC 测速可视化", desc: "UDP 延迟、丢包率、实际吞吐曲线——判断 Hysteria2 线路质量不再靠猜。" },
          { icon: Workflow, title: "与 TCP 协议混合编排", desc: "hy2 走 UDP 加速、vless 走 TCP 兜底，策略树里自由组合出口。" },
          { icon: Activity, title: "故障自动回退", desc: "UDP 被运营商 QoS 时自动切到 TCP 协议节点，不断流。" },
          { icon: Network, title: "全平台一致", desc: "桌面与移动端同一内核同一配置，Mesh 组网共享 hy2 出口。" },
        ],
        stepsTitle: "如何在 AirLane 里配置 Hysteria2",
        steps: [
          { title: "导入 hysteria2:// 链接", desc: "从服务商或自建服务器复制 hysteria2:// / hy2:// 分享链接，粘贴即导入——端口、密码、SNI、insecure 全部自动解析。" },
          { title: "选择出口策略", desc: "在策略树里把 Hysteria2 节点设为默认出口，或与 VLESS/Trojan 组成 UDP 加速 + TCP 兜底的混合策略。" },
          { title: "开启 TUN/系统代理", desc: "一键接管全局流量（TUN 模式）或仅系统代理，浏览器和 App 流量自动走 Hysteria2。" },
          { title: "测速与监控", desc: "内置延迟、丢包、吞吐曲线持续监控；UDP 被运营商限速时自动回退 TCP 节点，不断流。" },
        ],
        compareTitle: "命令行 vs AirLane 跑 Hysteria2",
        rivalName: "命令行/手写配置",
        comparison: [
          { capability: "配置方式", rival: "手写 YAML + 证书管理", airlane: "链接导入即用" },
          { capability: "自签证书", rival: "手动加 insecure 跳过", airlane: "自动识别处理" },
          { capability: "测速", rival: "外部工具", airlane: "内置延迟/丢包/吞吐" },
          { capability: "多协议混合", rival: "单协议配置", airlane: "hy2 + vless 策略组合" },
          { capability: "UDP 被限速", rival: "手动换节点", airlane: "自动回退 TCP" },
          { capability: "多端", rival: "各自维护", airlane: "Mesh 共享出口" },
        ],
        ctaTitle: "UDP 加速，图形化交付",
        ctaDesc: "导入你的 Hysteria2 节点，配合 VLESS 兜底策略，烂线路也能跑满。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "Hysteria2 Client for Windows, macOS, Android & iOS — AirLane GUI",
        desc: "AirLane is a plug-and-play Hysteria2 GUI client: paste a hysteria2:// share link to import, self-signed cert insecure handling is automatic, and latency tests, auto-switching and traffic stats are fully visual. All platforms, plus TUIC, VLESS Reality and 38+ protocols.",
        ogTitle: "AirLane — Hysteria2 GUI Client",
        ogDesc: "Paste hysteria2:// links to import; self-signed certs, speed tests and failover — all visual.",
        crumb: "Hysteria2 Client",
      },
      cfg: {
        badge: "Hysteria2 GUI Client",
        titlePre: "Plug-and-play",
        titleEm: "Hysteria2 Client",
        sub: "Hysteria2 saturates bandwidth on lossy routes over QUIC — but upstream only ships a CLI. AirLane turns it into a GUI client: paste a hysteria2:// link to import, insecure self-signed certs handled automatically, with visual speed tests, splitting and failover.",
        featuresTitle: "The AirLane Hysteria2 experience",
        featuresSub: "All of hy2's performance, none of the CLI.",
        features: [
          { icon: Zap, title: "Link-and-go import", desc: "Paste hysteria2:// / hy2:// links or subscriptions — port, password and SNI parsed automatically." },
          { icon: ShieldCheck, title: "Self-signed certs handled", desc: "Bare-IP nodes with insecure=1 are recognized automatically — no manual cert bypass errors." },
          { icon: Gauge, title: "Visual QUIC benchmarking", desc: "UDP latency, loss rate and real throughput curves — judge hy2 route quality with data." },
          { icon: Workflow, title: "Mix with TCP protocols", desc: "hy2 over UDP for speed, vless over TCP as fallback — compose exits freely in the policy tree." },
          { icon: Activity, title: "Automatic fallback", desc: "When carriers QoS UDP, AirLane fails over to TCP nodes automatically — no stream drops." },
          { icon: Network, title: "Consistent everywhere", desc: "Same core and config on desktop and mobile; Mesh shares hy2 exits across devices." },
        ],
        stepsTitle: "How to configure Hysteria2 in AirLane",
        steps: [
          { title: "Import a hysteria2:// link", desc: "Copy a hysteria2:// or hy2:// share link from your provider or self-hosted server and paste it — port, password, SNI and insecure flags are parsed automatically." },
          { title: "Pick an exit policy", desc: "Set the Hysteria2 node as your default exit in the policy tree, or combine it with VLESS/Trojan for a UDP-fast + TCP-fallback strategy." },
          { title: "Enable TUN or system proxy", desc: "Capture all traffic with one click (TUN mode) or just the system proxy — browsers and apps route through Hysteria2 automatically." },
          { title: "Benchmark and monitor", desc: "Built-in latency, packet-loss and throughput graphs; if your carrier throttles UDP, AirLane fails over to a TCP node without dropping streams." },
        ],
        compareTitle: "CLI vs AirLane for Hysteria2",
        rivalName: "CLI / manual config",
        comparison: [
          { capability: "Configuration", rival: "Hand-written YAML + certs", airlane: "Link import, ready" },
          { capability: "Self-signed certs", rival: "Manual insecure flag", airlane: "Auto-detected" },
          { capability: "Speed tests", rival: "External tools", airlane: "Built-in latency/loss/throughput" },
          { capability: "Protocol mixing", rival: "One config per run", airlane: "hy2 + vless policy combos" },
          { capability: "UDP throttled", rival: "Manual node swap", airlane: "Auto TCP fallback" },
          { capability: "Multi-device", rival: "Per-device configs", airlane: "Mesh shared exits" },
        ],
        ctaTitle: "UDP speed, delivered visually",
        ctaDesc: "Import your Hysteria2 nodes with a VLESS fallback policy — lossy routes still saturate.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },

  "vless-reality-client": {
    zh: {
      head: {
        title: "AirLane — VLESS Reality 可视化客户端 | VLESS Reality GUI",
        desc: "AirLane 是完整的 VLESS + Reality（xtls-rprx-vision）桌面客户端：vless:// 分享链接一键导入，Reality/vision flow 参数自动识别，配合策略树实现分流与健康自愈。Windows/macOS/Linux/Android/iOS 全平台，sing-box 内核，38+ 协议。",
        ogTitle: "AirLane — VLESS Reality 可视化客户端",
        ogDesc: "vless:// Reality 链接一键导入，xtls-rprx-vision 全支持，分流与健康自愈可视化。",
        crumb: "VLESS Reality 客户端",
      },
      cfg: {
        badge: "VLESS Reality 客户端",
        titlePre: "完整的",
        titleEm: "VLESS Reality 客户端",
        sub: "VLESS+Reality 是当前抗封锁最强的主流方案：TLS1.3 指纹 = 访问真实大站。AirLane 把它做成可视化客户端——vless:// 链接导入即识别 security=reality、flow=xtls-rprx-vision、SNI/pbk/sid 全套参数，无需理解协议细节。",
        featuresTitle: "AirLane 的 VLESS Reality 体验",
        featuresSub: "协议抗封锁上限，交给界面而不是配置文件。",
        features: [
          { icon: Zap, title: "vless:// 全参数识别", desc: "Reality pbk/sid/spx、flow、fp、SNI 自动解析，分享链接与订阅一键入库。" },
          { icon: ShieldCheck, title: "Vision flow 原生支持", desc: "xtls-rprx-vision 完整支持，TLS 指纹对外呈现真实站点行为。" },
          { icon: Workflow, title: "策略树分流", desc: "Reality 节点与其他协议节点任意组合：按域名/应用/地区分出口。" },
          { icon: Gauge, title: "节点健康评分", desc: "延迟、抖动、丢包评分驱动自动切换，Reality 节点异常不留死角。" },
          { icon: Activity, title: "流量仪表盘", desc: "每个出口实时吞吐与连接明细，验证流量确实走了 Reality 节点。" },
          { icon: Shield, title: "泄漏检测", desc: "DNS/WebRTC/IPv6 泄漏检测确保 Reality 隐匿性不被 DNS 侧信道破坏。" },
        ],
        compareTitle: "手写 sing-box config vs AirLane",
        rivalName: "手写配置",
        comparison: [
          { capability: "Reality 参数", rival: "手动填 uuid/pbk/sid/spx", airlane: "链接导入自动解析" },
          { capability: "flow 配置", rival: "容易漏掉 vision", airlane: "自动识别保留" },
          { capability: "分流", rival: "route.rules JSON", airlane: "可视化策略树" },
          { capability: "节点异常", rival: "手动排查", airlane: "评分 + 自动切换" },
          { capability: "泄漏防护", rival: "自行验证", airlane: "内置检测" },
          { capability: "多端", rival: "配置散落各设备", airlane: "Mesh 共享 + 订阅同步" },
        ],
        ctaTitle: "最强协议，最简单的用法",
        ctaDesc: "粘贴 vless:// Reality 链接，剩下的参数、分流和健康自愈交给 AirLane。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "AirLane — VLESS Reality GUI Client | Visual VLESS + Reality Desktop Client",
        desc: "AirLane is a complete VLESS + Reality (xtls-rprx-vision) desktop client: one-click vless:// share link import with automatic Reality/vision parameter parsing, visual policy trees and health-driven failover. All platforms, sing-box core, 38+ protocols.",
        ogTitle: "AirLane — VLESS Reality GUI Client",
        ogDesc: "vless:// Reality links import in one click — full xtls-rprx-vision support with visual routing.",
        crumb: "VLESS Reality Client",
      },
      cfg: {
        badge: "VLESS Reality Client",
        titlePre: "A Complete",
        titleEm: "VLESS Reality Client",
        sub: "VLESS+Reality is the strongest anti-blocking mainstream protocol today: TLS 1.3 fingerprints indistinguishable from visiting a real site. AirLane makes it visual — paste a vless:// link and security=reality, flow=xtls-rprx-vision, SNI/pbk/sid parse automatically. No protocol expertise required.",
        featuresTitle: "The AirLane VLESS Reality experience",
        featuresSub: "Maximum protocol stealth, delivered through a UI — not a config file.",
        features: [
          { icon: Zap, title: "Full vless:// parsing", desc: "Reality pbk/sid/spx, flow, fp and SNI auto-parsed — share links and subscriptions import in one click." },
          { icon: ShieldCheck, title: "Native vision flow", desc: "Full xtls-rprx-vision support — TLS fingerprints behave like the real camouflage site." },
          { icon: Workflow, title: "Policy-tree splitting", desc: "Mix Reality nodes with any other protocol: split by domain, app or region." },
          { icon: Gauge, title: "Node health scoring", desc: "Latency/jitter/loss scoring drives automatic failover — no dead Reality nodes left on." },
          { icon: Activity, title: "Traffic dashboard", desc: "Per-exit live throughput and connection detail — verify traffic actually rides Reality." },
          { icon: Shield, title: "Leak detection", desc: "DNS/WebRTC/IPv6 leak tests keep Reality's stealth from being broken by a DNS side channel." },
        ],
        compareTitle: "Hand-written sing-box config vs AirLane",
        rivalName: "Manual config",
        comparison: [
          { capability: "Reality params", rival: "Manual uuid/pbk/sid/spx", airlane: "Auto-parsed from link" },
          { capability: "flow config", rival: "Easy to miss vision", airlane: "Auto-detected, preserved" },
          { capability: "Splitting", rival: "route.rules JSON", airlane: "Visual policy tree" },
          { capability: "Node failure", rival: "Manual debugging", airlane: "Scoring + auto failover" },
          { capability: "Leak protection", rival: "Verify yourself", airlane: "Built-in tests" },
          { capability: "Multi-device", rival: "Scattered configs", airlane: "Mesh sharing + sync" },
        ],
        ctaTitle: "The strongest protocol, the simplest UX",
        ctaDesc: "Paste a vless:// Reality link — AirLane handles parameters, splitting and self-healing.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },
  "tuic-client": {
    zh: {
      head: {
        title: "TUIC 客户端 · TUIC GUI 桌面客户端 | AirLane",
        desc: "AirLane 是可视化 TUIC 客户端：粘贴 tuic:// 链接即导入，TUIC v5 QUIC 并发流、UDP relay 与延迟测速全图形化。Windows/macOS/Linux/Android/iOS 全平台，sing-box 内核同时支持 Hysteria2、VLESS 等 38+ 协议。",
        ogTitle: "TUIC 客户端 · TUIC GUI — AirLane",
        ogDesc: "tuic:// 链接一键导入，QUIC 并发与测速全可视化。",
        crumb: "TUIC 客户端",
      },
      cfg: {
        badge: "TUIC GUI 客户端",
        titlePre: "开箱即用的",
        titleEm: "TUIC 客户端",
        sub: "TUIC v5 用 QUIC 单连接并发流跑赢拥塞线路——但官方只有命令行。AirLane 提供图形客户端：粘贴 tuic:// 链接即导入，uuid/密码/SNI 自动解析，测速、分流、自动切换全部可视化。",
        featuresTitle: "AirLane 的 TUIC 体验",
        featuresSub: "TUIC v5 的全部性能，GUI 的全部便利。",
        features: [
          { icon: Zap, title: "链接即导入", desc: "直接粘贴 tuic:// 分享链接或订阅，uuid、token、alpn 参数自动解析入库。" },
          { icon: Gauge, title: "QUIC 测速可视化", desc: "UDP 延迟、丢包率、实际吞吐曲线——判断 TUIC 线路质量不靠猜。" },
          { icon: Workflow, title: "与 TCP 协议混合编排", desc: "TUIC 走 UDP 加速、vless 走 TCP 兜底，策略树里自由组合出口。" },
          { icon: Activity, title: "故障自动回退", desc: "UDP 被运营商 QoS 时自动切到 TCP 协议节点，不断流。" },
          { icon: ShieldCheck, title: "拥塞控制可调", desc: "bbr / cubic / new_reno 拥塞算法 GUI 里直接切换，不用改配置文件。" },
          { icon: Network, title: "全平台一致", desc: "桌面与移动端同一内核同一配置，Mesh 组网共享 TUIC 出口。" },
        ],
        stepsTitle: "如何在 AirLane 里配置 TUIC",
        steps: [
          { title: "导入 tuic:// 链接", desc: "从服务商或自建服务器复制 tuic:// 分享链接粘贴导入——uuid、密码、SNI、拥塞算法全部自动解析。" },
          { title: "选择出口策略", desc: "把 TUIC 节点设为默认出口，或与其他协议组成 UDP 加速 + TCP 兜底的混合策略。" },
          { title: "开启 TUN/系统代理", desc: "一键接管全局流量或仅系统代理，浏览器和 App 自动走 TUIC。" },
          { title: "测速与监控", desc: "延迟、丢包、吞吐持续监控；UDP 被限速时自动回退 TCP 节点。" },
        ],
        compareTitle: "命令行 vs AirLane 跑 TUIC",
        rivalName: "命令行/手写配置",
        comparison: [
          { capability: "配置方式", rival: "手写 JSON + 证书管理", airlane: "链接导入即用" },
          { capability: "拥塞算法", rival: "改配置重启", airlane: "界面直接切换" },
          { capability: "测速", rival: "外部工具", airlane: "内置延迟/丢包/吞吐" },
          { capability: "多协议混合", rival: "单协议配置", airlane: "TUIC + vless 策略组合" },
          { capability: "UDP 被限速", rival: "手动换节点", airlane: "自动回退 TCP" },
          { capability: "多端", rival: "各自维护", airlane: "Mesh 共享出口" },
        ],
        ctaTitle: "QUIC 加速，图形化交付",
        ctaDesc: "导入你的 TUIC 节点，配合 TCP 兜底策略，烂线路也能跑满。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "TUIC Client for Windows, macOS, Android & iOS — AirLane GUI",
        desc: "AirLane is a visual TUIC client: paste a tuic:// link to import, with TUIC v5 QUIC streams, UDP relay and latency tests all graphical. All platforms, plus Hysteria2, VLESS Reality and 38+ protocols via the sing-box core.",
        ogTitle: "TUIC Client · TUIC GUI — AirLane",
        ogDesc: "Paste tuic:// links to import; QUIC streams and speed tests — all visual.",
        crumb: "TUIC Client",
      },
      cfg: {
        badge: "TUIC GUI Client",
        titlePre: "Plug-and-play",
        titleEm: "TUIC Client",
        sub: "TUIC v5 beats congested routes with concurrent QUIC streams — but upstream only ships a CLI. AirLane is a GUI client: paste a tuic:// link to import, uuid/token/SNI parsed automatically, with visual speed tests, splitting and failover.",
        featuresTitle: "The AirLane TUIC experience",
        featuresSub: "All of TUIC v5's performance, none of the CLI.",
        features: [
          { icon: Zap, title: "Link-and-go import", desc: "Paste tuic:// links or subscriptions — uuid, token and alpn parsed automatically." },
          { icon: Gauge, title: "Visual QUIC benchmarking", desc: "UDP latency, loss rate and real throughput curves — judge route quality with data." },
          { icon: Workflow, title: "Mix with TCP protocols", desc: "TUIC over UDP for speed, vless over TCP as fallback — compose exits freely." },
          { icon: Activity, title: "Automatic fallback", desc: "When carriers throttle UDP, AirLane fails over to TCP nodes automatically." },
          { icon: ShieldCheck, title: "Tunable congestion control", desc: "Switch bbr / cubic / new_reno in the GUI — no config edits or restarts." },
          { icon: Network, title: "Consistent everywhere", desc: "Same core and config on desktop and mobile; Mesh shares TUIC exits." },
        ],
        stepsTitle: "How to configure TUIC in AirLane",
        steps: [
          { title: "Import a tuic:// link", desc: "Copy a tuic:// share link from your provider or self-hosted server and paste it — uuid, password, SNI and congestion control parse automatically." },
          { title: "Pick an exit policy", desc: "Set the TUIC node as your default exit, or combine it with other protocols for a UDP-fast + TCP-fallback strategy." },
          { title: "Enable TUN or system proxy", desc: "Capture all traffic with one click (TUN) or just the system proxy — apps route through TUIC automatically." },
          { title: "Benchmark and monitor", desc: "Latency, packet-loss and throughput graphs; UDP throttling triggers automatic TCP failover." },
        ],
        compareTitle: "CLI vs AirLane for TUIC",
        rivalName: "CLI / manual config",
        comparison: [
          { capability: "Configuration", rival: "Hand-written JSON + certs", airlane: "Link import, ready" },
          { capability: "Congestion control", rival: "Edit config, restart", airlane: "Switch in the GUI" },
          { capability: "Speed tests", rival: "External tools", airlane: "Built-in latency/loss/throughput" },
          { capability: "Protocol mixing", rival: "One config per run", airlane: "TUIC + vless combos" },
          { capability: "UDP throttled", rival: "Manual node swap", airlane: "Auto TCP fallback" },
          { capability: "Multi-device", rival: "Maintained separately", airlane: "Mesh-shared exits" },
        ],
        ctaTitle: "QUIC speed, GUI delivery",
        ctaDesc: "Import your TUIC nodes with a TCP fallback strategy — saturate even lossy routes.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },
  "trojan-client": {
    zh: {
      head: {
        title: "Trojan 客户端 · Trojan GUI 桌面客户端 | AirLane",
        desc: "AirLane 是可视化 Trojan 客户端：粘贴 trojan:// 链接即导入，TLS 伪装节点测速、分流、自动切换全图形化。Windows/macOS/Linux/Android/iOS 全平台，sing-box 内核同时支持 VLESS、Hysteria2 等 38+ 协议。",
        ogTitle: "Trojan 客户端 · Trojan GUI — AirLane",
        ogDesc: "trojan:// 链接一键导入，测速与分流全可视化。",
        crumb: "Trojan 客户端",
      },
      cfg: {
        badge: "Trojan GUI 客户端",
        titlePre: "开箱即用的",
        titleEm: "Trojan 客户端",
        sub: "Trojan 把代理流量伪装成 HTTPS 直达——隐蔽性强，但生态里缺少好用的桌面 GUI。AirLane 提供图形客户端：粘贴 trojan:// 链接即导入，密码/SNI 自动解析，测速、分流、自动切换全部可视化。",
        featuresTitle: "AirLane 的 Trojan 体验",
        featuresSub: "HTTPS 伪装的隐蔽性，GUI 的便利。",
        features: [
          { icon: Zap, title: "链接即导入", desc: "直接粘贴 trojan:// 分享链接或订阅，密码、SNI、端口自动解析入库。" },
          { icon: ShieldCheck, title: "TLS 伪装管理", desc: "SNI/fingerprint 参数可视化校验，证书异常节点自动标记。" },
          { icon: Gauge, title: "测速可视化", desc: "TLS 握手延迟、实际吞吐曲线——判断 Trojan 线路质量不靠猜。" },
          { icon: Workflow, title: "与 UDP 协议混合编排", desc: "Trojan 走 TCP 稳态、Hysteria2 走 UDP 加速，策略树自由组合出口。" },
          { icon: Activity, title: "故障自动切换", desc: "节点失联自动切换到备用出口，下载不断流。" },
          { icon: Network, title: "全平台一致", desc: "桌面与移动端同一内核同一配置，Mesh 组网共享 Trojan 出口。" },
        ],
        stepsTitle: "如何在 AirLane 里配置 Trojan",
        steps: [
          { title: "导入 trojan:// 链接", desc: "从服务商复制 trojan:// 分享链接粘贴导入——密码、SNI、端口全部自动解析。" },
          { title: "选择出口策略", desc: "把 Trojan 节点设为默认出口，或与 UDP 协议组成混合策略。" },
          { title: "开启 TUN/系统代理", desc: "一键接管全局流量或仅系统代理，浏览器和 App 自动走 Trojan。" },
          { title: "测速与监控", desc: "延迟与吞吐持续监控，节点失联自动切换备用出口。" },
        ],
        compareTitle: "传统客户端 vs AirLane 跑 Trojan",
        rivalName: "老旧 GUI / 手写配置",
        comparison: [
          { capability: "配置方式", rival: "手写 JSON / 导入冲突", airlane: "链接导入即用" },
          { capability: "TLS 校验", rival: "报错靠自己排查", airlane: "可视化标记" },
          { capability: "测速", rival: "外部工具", airlane: "内置延迟/吞吐" },
          { capability: "多协议混合", rival: "单协议配置", airlane: "Trojan + hy2 策略组合" },
          { capability: "故障切换", rival: "手动换节点", airlane: "自动切换" },
          { capability: "维护状态", rival: "多数已停更", airlane: "活跃维护" },
        ],
        ctaTitle: "隐蔽性不变，体验换代",
        ctaDesc: "导入你的 Trojan 节点，配合策略分流和故障自愈，伪装线路也能可视化。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "Trojan Client for Windows, macOS, Android & iOS — AirLane GUI",
        desc: "AirLane is a visual Trojan client: paste a trojan:// link to import, with TLS-camouflaged node benchmarking, routing and failover all graphical. All platforms, plus VLESS, Hysteria2 and 38+ protocols via the sing-box core.",
        ogTitle: "Trojan Client · Trojan GUI — AirLane",
        ogDesc: "Paste trojan:// links to import; benchmarking and routing — all visual.",
        crumb: "Trojan Client",
      },
      cfg: {
        badge: "Trojan GUI Client",
        titlePre: "Plug-and-play",
        titleEm: "Trojan Client",
        sub: "Trojan disguises proxy traffic as HTTPS — highly stealthy, but the ecosystem lacks a good desktop GUI. AirLane is a GUI client: paste a trojan:// link to import, password/SNI parsed automatically, with visual benchmarking, splitting and failover.",
        featuresTitle: "The AirLane Trojan experience",
        featuresSub: "HTTPS camouflage, GUI convenience.",
        features: [
          { icon: Zap, title: "Link-and-go import", desc: "Paste trojan:// links or subscriptions — password, SNI and port parsed automatically." },
          { icon: ShieldCheck, title: "TLS camouflage management", desc: "SNI/fingerprint params verified visually; nodes with cert anomalies are flagged." },
          { icon: Gauge, title: "Visual benchmarking", desc: "TLS handshake latency and real throughput curves — judge route quality with data." },
          { icon: Workflow, title: "Mix with UDP protocols", desc: "Trojan over TCP for stability, Hysteria2 over UDP for speed — compose exits freely." },
          { icon: Activity, title: "Automatic failover", desc: "Dead nodes trigger automatic switch to a backup exit — no dropped streams." },
          { icon: Network, title: "Consistent everywhere", desc: "Same core and config on desktop and mobile; Mesh shares Trojan exits." },
        ],
        stepsTitle: "How to configure Trojan in AirLane",
        steps: [
          { title: "Import a trojan:// link", desc: "Copy a trojan:// share link from your provider and paste it — password, SNI and port parse automatically." },
          { title: "Pick an exit policy", desc: "Set the Trojan node as your default exit, or combine it with UDP protocols in a mixed strategy." },
          { title: "Enable TUN or system proxy", desc: "Capture all traffic with one click (TUN) or just the system proxy — apps route through Trojan automatically." },
          { title: "Benchmark and monitor", desc: "Latency and throughput monitoring; dead nodes fail over to backups automatically." },
        ],
        compareTitle: "Legacy clients vs AirLane for Trojan",
        rivalName: "Legacy GUI / manual config",
        comparison: [
          { capability: "Configuration", rival: "Hand-written JSON / import conflicts", airlane: "Link import, ready" },
          { capability: "TLS validation", rival: "Debug errors yourself", airlane: "Visual flagging" },
          { capability: "Speed tests", rival: "External tools", airlane: "Built-in latency/throughput" },
          { capability: "Protocol mixing", rival: "One protocol per run", airlane: "Trojan + hy2 combos" },
          { capability: "Failover", rival: "Manual node swap", airlane: "Automatic" },
          { capability: "Maintenance", rival: "Mostly abandoned", airlane: "Actively maintained" },
        ],
        ctaTitle: "Same stealth, new experience",
        ctaDesc: "Import your Trojan nodes with policy routing and self-healing failover.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },
  "shadowsocks-client": {
    zh: {
      head: {
        title: "Shadowsocks 客户端 · SS GUI 桌面客户端 | AirLane",
        desc: "AirLane 是现代化 Shadowsocks 客户端：粘贴 ss:// 链接即导入，支持 SS2022 加密套件，测速、分流、自动切换全图形化。Windows/macOS/Linux/Android/iOS 全平台，sing-box 内核同时支持 VLESS、Hysteria2 等 38+ 协议。",
        ogTitle: "Shadowsocks 客户端 · SS GUI — AirLane",
        ogDesc: "ss:// 链接一键导入，SS2022 与测速全可视化。",
        crumb: "Shadowsocks 客户端",
      },
      cfg: {
        badge: "Shadowsocks GUI 客户端",
        titlePre: "现代",
        titleEm: "Shadowsocks 客户端",
        sub: "Shadowsocks 轻量、省电、多路复用优秀——但经典客户端要么停更要么界面老旧。AirLane 是新一代 SS 客户端：粘贴 ss:// 链接即导入，SS2022 加密套件原生支持，测速、分流、自动切换全部可视化。",
        featuresTitle: "AirLane 的 Shadowsocks 体验",
        featuresSub: "SS 的轻量，现代 GUI 的完整度。",
        features: [
          { icon: Zap, title: "链接即导入", desc: "直接粘贴 ss:// 分享链接或订阅，加密方式、密码、端口自动解析入库。" },
          { icon: ShieldCheck, title: "SS2022 原生支持", desc: "2022-blake3-aes-128-gcm 等新加密套件开箱即用，不用手动折腾插件。" },
          { icon: Gauge, title: "测速可视化", desc: "延迟、实际吞吐曲线——多 SS 节点一眼看出哪条最快。" },
          { icon: Workflow, title: "与现代协议混合编排", desc: "SS 省电跑日常、VLESS Reality 兜底，策略树自由组合出口。" },
          { icon: Activity, title: "故障自动切换", desc: "节点失联自动切换到备用出口，不断流。" },
          { icon: Network, title: "全平台一致", desc: "桌面与移动端同一内核同一配置，Mesh 组网共享 SS 出口。" },
        ],
        stepsTitle: "如何在 AirLane 里配置 Shadowsocks",
        steps: [
          { title: "导入 ss:// 链接", desc: "从服务商复制 ss:// 分享链接粘贴导入——加密方式、密码、端口全部自动解析。" },
          { title: "选择出口策略", desc: "把 SS 节点设为默认出口，或与其他协议组成混合策略。" },
          { title: "开启 TUN/系统代理", desc: "一键接管全局流量或仅系统代理，浏览器和 App 自动走 SS。" },
          { title: "测速与监控", desc: "延迟与吞吐持续监控，节点失联自动切换备用出口。" },
        ],
        compareTitle: "经典 SS 客户端 vs AirLane",
        rivalName: "老旧 SS 客户端",
        comparison: [
          { capability: "维护状态", rival: "多数停更", airlane: "活跃维护" },
          { capability: "SS2022", rival: "需插件或不支持", airlane: "原生支持" },
          { capability: "测速", rival: "外部工具", airlane: "内置延迟/吞吐" },
          { capability: "多协议", rival: "仅 SS", airlane: "38+ 协议统一出口" },
          { capability: "故障切换", rival: "手动换节点", airlane: "自动切换" },
          { capability: "多端", rival: "各自维护", airlane: "Mesh 共享出口" },
        ],
        ctaTitle: "轻量协议，现代客户端",
        ctaDesc: "导入你的 Shadowsocks 节点，和老旧 GUI 说再见。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "Shadowsocks Client for Windows, macOS, Android & iOS — AirLane GUI",
        desc: "AirLane is a modern Shadowsocks client: paste an ss:// link to import, with native SS2022 cipher support and benchmarking, routing and failover all graphical. All platforms, plus VLESS, Hysteria2 and 38+ protocols via the sing-box core.",
        ogTitle: "Shadowsocks Client · SS GUI — AirLane",
        ogDesc: "Paste ss:// links to import; SS2022 and benchmarking — all visual.",
        crumb: "Shadowsocks Client",
      },
      cfg: {
        badge: "Shadowsocks GUI Client",
        titlePre: "A modern",
        titleEm: "Shadowsocks Client",
        sub: "Shadowsocks is lightweight, battery-friendly and multiplexes well — but classic clients are abandoned or dated. AirLane is the next-gen SS client: paste an ss:// link to import, SS2022 ciphers supported natively, with visual benchmarking, splitting and failover.",
        featuresTitle: "The AirLane Shadowsocks experience",
        featuresSub: "SS's lightness, a modern GUI's completeness.",
        features: [
          { icon: Zap, title: "Link-and-go import", desc: "Paste ss:// links or subscriptions — cipher, password and port parsed automatically." },
          { icon: ShieldCheck, title: "Native SS2022", desc: "2022-blake3-aes-128-gcm and friends work out of the box — no plugins needed." },
          { icon: Gauge, title: "Visual benchmarking", desc: "Latency and real throughput curves — see which SS node is fastest at a glance." },
          { icon: Workflow, title: "Mix with modern protocols", desc: "SS for daily battery-friendly traffic, VLESS Reality as fallback — compose freely." },
          { icon: Activity, title: "Automatic failover", desc: "Dead nodes trigger automatic switch to a backup exit — no dropped streams." },
          { icon: Network, title: "Consistent everywhere", desc: "Same core and config on desktop and mobile; Mesh shares SS exits." },
        ],
        stepsTitle: "How to configure Shadowsocks in AirLane",
        steps: [
          { title: "Import an ss:// link", desc: "Copy an ss:// share link from your provider and paste it — cipher, password and port parse automatically." },
          { title: "Pick an exit policy", desc: "Set the SS node as your default exit, or combine it with other protocols in a mixed strategy." },
          { title: "Enable TUN or system proxy", desc: "Capture all traffic with one click (TUN) or just the system proxy — apps route through SS automatically." },
          { title: "Benchmark and monitor", desc: "Latency and throughput monitoring; dead nodes fail over to backups automatically." },
        ],
        compareTitle: "Classic SS clients vs AirLane",
        rivalName: "Legacy SS clients",
        comparison: [
          { capability: "Maintenance", rival: "Mostly abandoned", airlane: "Actively maintained" },
          { capability: "SS2022", rival: "Plugins or unsupported", airlane: "Native" },
          { capability: "Speed tests", rival: "External tools", airlane: "Built-in latency/throughput" },
          { capability: "Protocols", rival: "SS only", airlane: "38+ unified exits" },
          { capability: "Failover", rival: "Manual node swap", airlane: "Automatic" },
          { capability: "Multi-device", rival: "Maintained separately", airlane: "Mesh-shared exits" },
        ],
        ctaTitle: "Lightweight protocol, modern client",
        ctaDesc: "Import your Shadowsocks nodes and say goodbye to dated GUIs.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },
  "vmess-client": {
    zh: {
      head: {
        title: "VMess 客户端 · VMess GUI 桌面客户端 | AirLane",
        desc: "AirLane 是可视化 VMess 客户端：粘贴 vmess:// 链接即导入，WebSocket/TLS 传输参数自动解析，测速、分流、自动切换全图形化。Windows/macOS/Linux/Android/iOS 全平台，sing-box 内核同时支持 VLESS、Hysteria2 等 38+ 协议。",
        ogTitle: "VMess 客户端 · VMess GUI — AirLane",
        ogDesc: "vmess:// 链接一键导入，WS/TLS 参数自动解析。",
        crumb: "VMess 客户端",
      },
      cfg: {
        badge: "VMess GUI 客户端",
        titlePre: "开箱即用的",
        titleEm: "VMess 客户端",
        sub: "VMess 节点存量巨大——机场订阅、自建服务器到处都在用。AirLane 是可视化 VMess 客户端：粘贴 vmess:// 链接即导入，WS path/host、TLS、alterId 全部自动解析，测速、分流、自动切换全部可视化。",
        featuresTitle: "AirLane 的 VMess 体验",
        featuresSub: "存量节点的兼容性，现代客户端的完整度。",
        features: [
          { icon: Zap, title: "链接即导入", desc: "直接粘贴 vmess:// 分享链接或订阅，uuid、WS/TLS 参数自动解析入库。" },
          { icon: ShieldCheck, title: "传输层可视", desc: "WebSocket path/host、TLS SNI、CDN 节点参数一目了然，配置错误自动标记。" },
          { icon: Gauge, title: "测速可视化", desc: "延迟、实际吞吐曲线——CDN 中转节点质量一眼可辨。" },
          { icon: Workflow, title: "与新协议混合编排", desc: "VMess 存量节点 + VLESS Reality 新节点统一策略树，按规则分流。" },
          { icon: Activity, title: "故障自动切换", desc: "节点失联自动切换到备用出口，不断流。" },
          { icon: Network, title: "全平台一致", desc: "桌面与移动端同一内核同一配置，Mesh 组网共享 VMess 出口。" },
        ],
        stepsTitle: "如何在 AirLane 里配置 VMess",
        steps: [
          { title: "导入 vmess:// 链接", desc: "从服务商复制 vmess:// 分享链接或订阅地址粘贴导入——uuid、WS/TLS 参数全部自动解析。" },
          { title: "选择出口策略", desc: "把 VMess 节点设为默认出口，或与其他协议组成混合策略。" },
          { title: "开启 TUN/系统代理", desc: "一键接管全局流量或仅系统代理，浏览器和 App 自动走 VMess。" },
          { title: "测速与监控", desc: "延迟与吞吐持续监控，节点失联自动切换备用出口。" },
        ],
        compareTitle: "手写 JSON vs AirLane 跑 VMess",
        rivalName: "手写配置/老旧客户端",
        comparison: [
          { capability: "配置方式", rival: "手写 JSON 易错", airlane: "链接导入即用" },
          { capability: "WS/TLS 参数", rival: "字段含义靠查文档", airlane: "可视化校验" },
          { capability: "测速", rival: "外部工具", airlane: "内置延迟/吞吐" },
          { capability: "多协议", rival: "仅 VMess", airlane: "38+ 协议统一出口" },
          { capability: "故障切换", rival: "手动换节点", airlane: "自动切换" },
          { capability: "多端", rival: "各自维护", airlane: "Mesh 共享出口" },
        ],
        ctaTitle: "存量节点，现代体验",
        ctaDesc: "导入你的 VMess 节点和订阅，统一管理、可视化测速、自动切换。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "VMess Client for Windows, macOS, Android & iOS — AirLane GUI",
        desc: "AirLane is a visual VMess client: paste a vmess:// link to import, with WebSocket/TLS transport params parsed automatically and benchmarking, routing and failover all graphical. All platforms, plus VLESS, Hysteria2 and 38+ protocols via the sing-box core.",
        ogTitle: "VMess Client · VMess GUI — AirLane",
        ogDesc: "Paste vmess:// links to import; WS/TLS params parsed automatically.",
        crumb: "VMess Client",
      },
      cfg: {
        badge: "VMess GUI Client",
        titlePre: "Plug-and-play",
        titleEm: "VMess Client",
        sub: "VMess nodes are everywhere — airport subscriptions, self-hosted servers. AirLane is a visual VMess client: paste a vmess:// link to import, WS path/host, TLS and alterId parsed automatically, with visual benchmarking, splitting and failover.",
        featuresTitle: "The AirLane VMess experience",
        featuresSub: "Legacy-node compatibility, modern-client completeness.",
        features: [
          { icon: Zap, title: "Link-and-go import", desc: "Paste vmess:// links or subscriptions — uuid, WS/TLS params parsed automatically." },
          { icon: ShieldCheck, title: "Visual transport layer", desc: "WebSocket path/host, TLS SNI and CDN params at a glance; misconfigurations flagged." },
          { icon: Gauge, title: "Visual benchmarking", desc: "Latency and real throughput curves — judge CDN-relay node quality instantly." },
          { icon: Workflow, title: "Mix with modern protocols", desc: "Legacy VMess nodes + VLESS Reality in one policy tree, routed by rules." },
          { icon: Activity, title: "Automatic failover", desc: "Dead nodes trigger automatic switch to a backup exit — no dropped streams." },
          { icon: Network, title: "Consistent everywhere", desc: "Same core and config on desktop and mobile; Mesh shares VMess exits." },
        ],
        stepsTitle: "How to configure VMess in AirLane",
        steps: [
          { title: "Import a vmess:// link", desc: "Copy a vmess:// share link or subscription from your provider and paste it — uuid and WS/TLS params parse automatically." },
          { title: "Pick an exit policy", desc: "Set the VMess node as your default exit, or combine it with other protocols in a mixed strategy." },
          { title: "Enable TUN or system proxy", desc: "Capture all traffic with one click (TUN) or just the system proxy — apps route through VMess automatically." },
          { title: "Benchmark and monitor", desc: "Latency and throughput monitoring; dead nodes fail over to backups automatically." },
        ],
        compareTitle: "Hand-written JSON vs AirLane for VMess",
        rivalName: "Manual config / legacy clients",
        comparison: [
          { capability: "Configuration", rival: "Error-prone JSON", airlane: "Link import, ready" },
          { capability: "WS/TLS params", rival: "Look up field docs", airlane: "Visual validation" },
          { capability: "Speed tests", rival: "External tools", airlane: "Built-in latency/throughput" },
          { capability: "Protocols", rival: "VMess only", airlane: "38+ unified exits" },
          { capability: "Failover", rival: "Manual node swap", airlane: "Automatic" },
          { capability: "Multi-device", rival: "Maintained separately", airlane: "Mesh-shared exits" },
        ],
        ctaTitle: "Legacy nodes, modern experience",
        ctaDesc: "Import your VMess nodes and subscriptions — unified management, visual benchmarks, automatic failover.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },
  "wireguard-client": {
    zh: {
      head: {
        title: "WireGuard 客户端 · WireGuard GUI 管理器 | AirLane",
        desc: "AirLane 是可视化 WireGuard 客户端与管理器：粘贴 wg 配置或链接即导入，多 peer 隧道管理、分流规则、测速全图形化。Windows/macOS/Linux/Android/iOS 全平台，sing-box 内核同时支持 VLESS、Hysteria2 等 38+ 协议。",
        ogTitle: "WireGuard 客户端 · WireGuard GUI — AirLane",
        ogDesc: "wg 配置一键导入，多隧道与分流全可视化。",
        crumb: "WireGuard 客户端",
      },
      cfg: {
        badge: "WireGuard GUI 客户端",
        titlePre: "可视化",
        titleEm: "WireGuard 管理器",
        sub: "WireGuard 快而省电，但官方客户端只管一条隧道、没有分流。AirLane 把 WireGuard 变成可编排的出口：导入 peer 配置即上线，按域名/IP 分流进不同隧道，测速、监控、自动切换全部可视化——还能和代理协议混跑。",
        featuresTitle: "AirLane 的 WireGuard 体验",
        featuresSub: "不止连接，还能编排。",
        features: [
          { icon: Zap, title: "配置即导入", desc: "粘贴 WireGuard 配置或分享链接——私钥、Endpoint、AllowedIPs 自动解析。" },
          { icon: Workflow, title: "多隧道分流", desc: "按域名/IP/应用把流量路由进不同 WireGuard 隧道或代理出口——官方客户端做不到。" },
          { icon: Gauge, title: "隧道测速", desc: "握手延迟、实际吞吐曲线——多条 WireGuard 隧道质量一眼可辨。" },
          { icon: ShieldCheck, title: "密钥安全存储", desc: "私钥进系统凭据库，不落明文配置文件。" },
          { icon: Activity, title: "故障自动切换", desc: "隧道失联自动切换到备用出口，不断流。" },
          { icon: Network, title: "全平台一致", desc: "桌面与移动端同一内核同一配置，Mesh 组网共享 WireGuard 出口。" },
        ],
        stepsTitle: "如何在 AirLane 里配置 WireGuard",
        steps: [
          { title: "导入 WireGuard 配置", desc: "粘贴 wg 配置文件内容或分享链接——私钥、Endpoint、AllowedIPs 全部自动解析。" },
          { title: "选择出口策略", desc: "把 WireGuard 隧道设为默认出口，或按规则把特定域名/IP 分流进隧道。" },
          { title: "开启 TUN/系统代理", desc: "一键接管全局流量，浏览器和 App 按策略自动走 WireGuard。" },
          { title: "测速与监控", desc: "握手延迟与吞吐持续监控，隧道失联自动切换备用出口。" },
        ],
        compareTitle: "官方客户端 vs AirLane 跑 WireGuard",
        rivalName: "官方客户端 / wg-quick",
        comparison: [
          { capability: "隧道数量", rival: "一次一条", airlane: "多隧道按策略分流" },
          { capability: "分流", rival: "无（AllowedIPs 硬编码）", airlane: "域名/IP/应用规则" },
          { capability: "测速", rival: "无", airlane: "内置延迟/吞吐" },
          { capability: "密钥存储", rival: "明文配置目录", airlane: "系统凭据库" },
          { capability: "故障切换", rival: "手动切隧道", airlane: "自动切换" },
          { capability: "与代理混跑", rival: "不支持", airlane: "WG + VLESS/Hy2 策略组合" },
        ],
        ctaTitle: "WireGuard 不止于连接",
        ctaDesc: "导入你的 WireGuard 隧道，体验多隧道分流和自动切换。",
        ctaLabel: "免费下载",
        ctaTo: "/download",
      },
    },
    en: {
      head: {
        title: "WireGuard Client for Windows, macOS, Android & iOS — AirLane GUI",
        desc: "AirLane is a visual WireGuard client and manager: import wg configs or links, manage multiple peer tunnels, route traffic by rules and benchmark — all graphical. All platforms, plus VLESS, Hysteria2 and 38+ protocols via the sing-box core.",
        ogTitle: "WireGuard Client · WireGuard GUI — AirLane",
        ogDesc: "Import wg configs; multi-tunnel routing and benchmarking — all visual.",
        crumb: "WireGuard Client",
      },
      cfg: {
        badge: "WireGuard GUI Manager",
        titlePre: "A visual",
        titleEm: "WireGuard Manager",
        sub: "WireGuard is fast and battery-friendly, but the official client handles a single tunnel with no routing. AirLane turns WireGuard into an orchestrable exit: import a peer config and go live, route domains/IPs into different tunnels, with benchmarking, monitoring and failover — and it can mix with proxy protocols.",
        featuresTitle: "The AirLane WireGuard experience",
        featuresSub: "Beyond connecting — orchestrating.",
        features: [
          { icon: Zap, title: "Config-and-go import", desc: "Paste a WireGuard config or share link — private key, endpoint and AllowedIPs parsed automatically." },
          { icon: Workflow, title: "Multi-tunnel routing", desc: "Route domains/IPs/apps into different WireGuard tunnels or proxy exits — impossible in the official client." },
          { icon: Gauge, title: "Tunnel benchmarking", desc: "Handshake latency and real throughput curves — compare tunnel quality at a glance." },
          { icon: ShieldCheck, title: "Secure key storage", desc: "Private keys go into the system credential store — never plaintext config files." },
          { icon: Activity, title: "Automatic failover", desc: "Dead tunnels trigger automatic switch to a backup exit — no dropped streams." },
          { icon: Network, title: "Consistent everywhere", desc: "Same core and config on desktop and mobile; Mesh shares WireGuard exits." },
        ],
        stepsTitle: "How to configure WireGuard in AirLane",
        steps: [
          { title: "Import a WireGuard config", desc: "Paste your wg config or a share link — private key, endpoint and AllowedIPs parse automatically." },
          { title: "Pick an exit policy", desc: "Set the WireGuard tunnel as your default exit, or route specific domains/IPs into it by rules." },
          { title: "Enable TUN or system proxy", desc: "Capture all traffic with one click — browsers and apps route through WireGuard per your policy." },
          { title: "Benchmark and monitor", desc: "Handshake latency and throughput monitoring; dead tunnels fail over automatically." },
        ],
        compareTitle: "Official client vs AirLane for WireGuard",
        rivalName: "Official client / wg-quick",
        comparison: [
          { capability: "Tunnels", rival: "One at a time", airlane: "Multi-tunnel policy routing" },
          { capability: "Split routing", rival: "None (AllowedIPs hardcoded)", airlane: "Domain/IP/app rules" },
          { capability: "Speed tests", rival: "None", airlane: "Built-in latency/throughput" },
          { capability: "Key storage", rival: "Plaintext config dir", airlane: "System credential store" },
          { capability: "Failover", rival: "Manual tunnel swap", airlane: "Automatic" },
          { capability: "Proxy mixing", rival: "Unsupported", airlane: "WG + VLESS/Hy2 combos" },
        ],
        ctaTitle: "WireGuard beyond connecting",
        ctaDesc: "Import your WireGuard tunnels and get multi-tunnel routing with automatic failover.",
        ctaLabel: "Download Free",
        ctaTo: "/en/download",
      },
    },
  },
};
