/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ClashAlternativeRouteImport } from './routes/clash-alternative'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EnRouteImport } from './routes/en'
import { Route as HiddifyAlternativeRouteImport } from './routes/hiddify-alternative'
import { Route as Hysteria2ClientRouteImport } from './routes/hysteria2-client'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as MihomoAlternativeRouteImport } from './routes/mihomo-alternative'
import { Route as NekoboxAlternativeRouteImport } from './routes/nekobox-alternative'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SingBoxGuiRouteImport } from './routes/sing-box-gui'
import { Route as SitemapBlogDotxmlRouteImport } from './routes/sitemap-blog[.]xml'
import { Route as SitemapDocsDotxmlRouteImport } from './routes/sitemap-docs[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as V2raynAlternativeRouteImport } from './routes/v2rayn-alternative'
import { Route as VlessRealityClientRouteImport } from './routes/vless-reality-client'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogAdminRouteImport } from './routes/blog.admin'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DocsAdminRouteImport } from './routes/docs.admin'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnBlogRouteImport } from './routes/en.blog'
import { Route as EnClashAlternativeRouteImport } from './routes/en.clash-alternative'
import { Route as EnDocsRouteImport } from './routes/en.docs'
import { Route as EnDownloadRouteImport } from './routes/en.download'
import { Route as EnHiddifyAlternativeRouteImport } from './routes/en.hiddify-alternative'
import { Route as EnHysteria2ClientRouteImport } from './routes/en.hysteria2-client'
import { Route as EnMigrationRouteImport } from './routes/en.migration'
import { Route as EnMihomoAlternativeRouteImport } from './routes/en.mihomo-alternative'
import { Route as EnNekoboxAlternativeRouteImport } from './routes/en.nekobox-alternative'
import { Route as EnPrivacyRouteImport } from './routes/en.privacy'
import { Route as EnSingBoxGuiRouteImport } from './routes/en.sing-box-gui'
import { Route as EnTermsRouteImport } from './routes/en.terms'
import { Route as EnV2raynAlternativeRouteImport } from './routes/en.v2rayn-alternative'
import { Route as EnVlessRealityClientRouteImport } from './routes/en.vless-reality-client'
import { Route as ApiReleasesLatestRouteImport } from './routes/api/releases/latest'
import { Route as EnBlogIndexRouteImport } from './routes/en.blog.index'
import { Route as EnBlogSlugRouteImport } from './routes/en.blog.$slug'
import { Route as EnDocsIndexRouteImport } from './routes/en.docs.index'
import { Route as EnDocsSlugRouteImport } from './routes/en.docs.$slug'
import { Route as ApiPublicDevicesResourcesRouteImport } from './routes/api/public/devices/resources'
import { Route as ApiPublicDevicesStatusRouteImport } from './routes/api/public/devices/status'
import { Route as ApiPublicPairClaimRouteImport } from './routes/api/public/pair/claim'
import { Route as ApiPublicPairHeartbeatRouteImport } from './routes/api/public/pair/heartbeat'
import { Route as ApiReleasesDownloadFilenameRouteImport } from './routes/api/releases/download.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClashAlternativeRoute = ClashAlternativeRouteImport.update({
  id: '/clash-alternative',
  path: '/clash-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddifyAlternativeRoute = HiddifyAlternativeRouteImport.update({
  id: '/hiddify-alternative',
  path: '/hiddify-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const Hysteria2ClientRoute = Hysteria2ClientRouteImport.update({
  id: '/hysteria2-client',
  path: '/hysteria2-client',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const MihomoAlternativeRoute = MihomoAlternativeRouteImport.update({
  id: '/mihomo-alternative',
  path: '/mihomo-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const NekoboxAlternativeRoute = NekoboxAlternativeRouteImport.update({
  id: '/nekobox-alternative',
  path: '/nekobox-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SingBoxGuiRoute = SingBoxGuiRouteImport.update({
  id: '/sing-box-gui',
  path: '/sing-box-gui',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogDotxmlRoute = SitemapBlogDotxmlRouteImport.update({
  id: '/sitemap-blog.xml',
  path: '/sitemap-blog.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDocsDotxmlRoute = SitemapDocsDotxmlRouteImport.update({
  id: '/sitemap-docs.xml',
  path: '/sitemap-docs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const V2raynAlternativeRoute = V2raynAlternativeRouteImport.update({
  id: '/v2rayn-alternative',
  path: '/v2rayn-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const VlessRealityClientRoute = VlessRealityClientRouteImport.update({
  id: '/vless-reality-client',
  path: '/vless-reality-client',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAdminRoute = BlogAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BlogRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAdminRoute = DocsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DocsRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnBlogRoute = EnBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => EnRoute,
} as any)
const EnClashAlternativeRoute = EnClashAlternativeRouteImport.update({
  id: '/clash-alternative',
  path: '/clash-alternative',
  getParentRoute: () => EnRoute,
} as any)
const EnDocsRoute = EnDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => EnRoute,
} as any)
const EnDownloadRoute = EnDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => EnRoute,
} as any)
const EnHiddifyAlternativeRoute = EnHiddifyAlternativeRouteImport.update({
  id: '/hiddify-alternative',
  path: '/hiddify-alternative',
  getParentRoute: () => EnRoute,
} as any)
const EnHysteria2ClientRoute = EnHysteria2ClientRouteImport.update({
  id: '/hysteria2-client',
  path: '/hysteria2-client',
  getParentRoute: () => EnRoute,
} as any)
const EnMigrationRoute = EnMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => EnRoute,
} as any)
const EnMihomoAlternativeRoute = EnMihomoAlternativeRouteImport.update({
  id: '/mihomo-alternative',
  path: '/mihomo-alternative',
  getParentRoute: () => EnRoute,
} as any)
const EnNekoboxAlternativeRoute = EnNekoboxAlternativeRouteImport.update({
  id: '/nekobox-alternative',
  path: '/nekobox-alternative',
  getParentRoute: () => EnRoute,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EnRoute,
} as any)
const EnSingBoxGuiRoute = EnSingBoxGuiRouteImport.update({
  id: '/sing-box-gui',
  path: '/sing-box-gui',
  getParentRoute: () => EnRoute,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EnRoute,
} as any)
const EnV2raynAlternativeRoute = EnV2raynAlternativeRouteImport.update({
  id: '/v2rayn-alternative',
  path: '/v2rayn-alternative',
  getParentRoute: () => EnRoute,
} as any)
const EnVlessRealityClientRoute = EnVlessRealityClientRouteImport.update({
  id: '/vless-reality-client',
  path: '/vless-reality-client',
  getParentRoute: () => EnRoute,
} as any)
const ApiReleasesLatestRoute = ApiReleasesLatestRouteImport.update({
  id: '/api/releases/latest',
  path: '/api/releases/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogIndexRoute = EnBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnBlogRoute,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnBlogRoute,
} as any)
const EnDocsIndexRoute = EnDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnDocsRoute,
} as any)
const EnDocsSlugRoute = EnDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnDocsRoute,
} as any)
const ApiPublicDevicesResourcesRoute =
  ApiPublicDevicesResourcesRouteImport.update({
    id: '/api/public/devices/resources',
    path: '/api/public/devices/resources',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevicesStatusRoute = ApiPublicDevicesStatusRouteImport.update({
  id: '/api/public/devices/status',
  path: '/api/public/devices/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairClaimRoute = ApiPublicPairClaimRouteImport.update({
  id: '/api/public/pair/claim',
  path: '/api/public/pair/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairHeartbeatRoute = ApiPublicPairHeartbeatRouteImport.update({
  id: '/api/public/pair/heartbeat',
  path: '/api/public/pair/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleasesDownloadFilenameRoute =
  ApiReleasesDownloadFilenameRouteImport.update({
    id: '/api/releases/download/$filename',
    path: '/api/releases/download/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/clash-alternative': typeof ClashAlternativeRoute
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/en': typeof EnRouteWithChildren
  '/hiddify-alternative': typeof HiddifyAlternativeRoute
  '/hysteria2-client': typeof Hysteria2ClientRoute
  '/migration': typeof MigrationRoute
  '/mihomo-alternative': typeof MihomoAlternativeRoute
  '/nekobox-alternative': typeof NekoboxAlternativeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sing-box-gui': typeof SingBoxGuiRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-docs.xml': typeof SitemapDocsDotxmlRoute
  '/terms': typeof TermsRoute
  '/v2rayn-alternative': typeof V2raynAlternativeRoute
  '/vless-reality-client': typeof VlessRealityClientRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/clash-alternative': typeof EnClashAlternativeRoute
  '/en/docs': typeof EnDocsRouteWithChildren
  '/en/download': typeof EnDownloadRoute
  '/en/hiddify-alternative': typeof EnHiddifyAlternativeRoute
  '/en/hysteria2-client': typeof EnHysteria2ClientRoute
  '/en/migration': typeof EnMigrationRoute
  '/en/mihomo-alternative': typeof EnMihomoAlternativeRoute
  '/en/nekobox-alternative': typeof EnNekoboxAlternativeRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/sing-box-gui': typeof EnSingBoxGuiRoute
  '/en/terms': typeof EnTermsRoute
  '/en/v2rayn-alternative': typeof EnV2raynAlternativeRoute
  '/en/vless-reality-client': typeof EnVlessRealityClientRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/en/': typeof EnIndexRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
  '/en/docs/': typeof EnDocsIndexRoute
  '/api/public/devices/resources': typeof ApiPublicDevicesResourcesRoute
  '/api/public/devices/status': typeof ApiPublicDevicesStatusRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
  '/api/releases/download/$filename': typeof ApiReleasesDownloadFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/clash-alternative': typeof ClashAlternativeRoute
  '/devices': typeof DevicesRoute
  '/download': typeof DownloadRoute
  '/hiddify-alternative': typeof HiddifyAlternativeRoute
  '/hysteria2-client': typeof Hysteria2ClientRoute
  '/migration': typeof MigrationRoute
  '/mihomo-alternative': typeof MihomoAlternativeRoute
  '/nekobox-alternative': typeof NekoboxAlternativeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sing-box-gui': typeof SingBoxGuiRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-docs.xml': typeof SitemapDocsDotxmlRoute
  '/terms': typeof TermsRoute
  '/v2rayn-alternative': typeof V2raynAlternativeRoute
  '/vless-reality-client': typeof VlessRealityClientRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/en/clash-alternative': typeof EnClashAlternativeRoute
  '/en/download': typeof EnDownloadRoute
  '/en/hiddify-alternative': typeof EnHiddifyAlternativeRoute
  '/en/hysteria2-client': typeof EnHysteria2ClientRoute
  '/en/migration': typeof EnMigrationRoute
  '/en/mihomo-alternative': typeof EnMihomoAlternativeRoute
  '/en/nekobox-alternative': typeof EnNekoboxAlternativeRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/sing-box-gui': typeof EnSingBoxGuiRoute
  '/en/terms': typeof EnTermsRoute
  '/en/v2rayn-alternative': typeof EnV2raynAlternativeRoute
  '/en/vless-reality-client': typeof EnVlessRealityClientRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/en': typeof EnIndexRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/blog': typeof EnBlogIndexRoute
  '/en/docs': typeof EnDocsIndexRoute
  '/api/public/devices/resources': typeof ApiPublicDevicesResourcesRoute
  '/api/public/devices/status': typeof ApiPublicDevicesStatusRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
  '/api/releases/download/$filename': typeof ApiReleasesDownloadFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/clash-alternative': typeof ClashAlternativeRoute
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/en': typeof EnRouteWithChildren
  '/hiddify-alternative': typeof HiddifyAlternativeRoute
  '/hysteria2-client': typeof Hysteria2ClientRoute
  '/migration': typeof MigrationRoute
  '/mihomo-alternative': typeof MihomoAlternativeRoute
  '/nekobox-alternative': typeof NekoboxAlternativeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sing-box-gui': typeof SingBoxGuiRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-docs.xml': typeof SitemapDocsDotxmlRoute
  '/terms': typeof TermsRoute
  '/v2rayn-alternative': typeof V2raynAlternativeRoute
  '/vless-reality-client': typeof VlessRealityClientRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/clash-alternative': typeof EnClashAlternativeRoute
  '/en/docs': typeof EnDocsRouteWithChildren
  '/en/download': typeof EnDownloadRoute
  '/en/hiddify-alternative': typeof EnHiddifyAlternativeRoute
  '/en/hysteria2-client': typeof EnHysteria2ClientRoute
  '/en/migration': typeof EnMigrationRoute
  '/en/mihomo-alternative': typeof EnMihomoAlternativeRoute
  '/en/nekobox-alternative': typeof EnNekoboxAlternativeRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/sing-box-gui': typeof EnSingBoxGuiRoute
  '/en/terms': typeof EnTermsRoute
  '/en/v2rayn-alternative': typeof EnV2raynAlternativeRoute
  '/en/vless-reality-client': typeof EnVlessRealityClientRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/en/': typeof EnIndexRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
  '/en/docs/': typeof EnDocsIndexRoute
  '/api/public/devices/resources': typeof ApiPublicDevicesResourcesRoute
  '/api/public/devices/status': typeof ApiPublicDevicesStatusRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
  '/api/releases/download/$filename': typeof ApiReleasesDownloadFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/clash-alternative'
    | '/devices'
    | '/docs'
    | '/download'
    | '/en'
    | '/hiddify-alternative'
    | '/hysteria2-client'
    | '/migration'
    | '/mihomo-alternative'
    | '/nekobox-alternative'
    | '/privacy'
    | '/reset-password'
    | '/sing-box-gui'
    | '/sitemap-blog.xml'
    | '/sitemap-docs.xml'
    | '/terms'
    | '/v2rayn-alternative'
    | '/vless-reality-client'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/en/blog'
    | '/en/clash-alternative'
    | '/en/docs'
    | '/en/download'
    | '/en/hiddify-alternative'
    | '/en/hysteria2-client'
    | '/en/migration'
    | '/en/mihomo-alternative'
    | '/en/nekobox-alternative'
    | '/en/privacy'
    | '/en/sing-box-gui'
    | '/en/terms'
    | '/en/v2rayn-alternative'
    | '/en/vless-reality-client'
    | '/blog/'
    | '/docs/'
    | '/en/'
    | '/api/releases/latest'
    | '/en/blog/$slug'
    | '/en/docs/$slug'
    | '/en/blog/'
    | '/en/docs/'
    | '/api/public/devices/resources'
    | '/api/public/devices/status'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
    | '/api/releases/download/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/clash-alternative'
    | '/devices'
    | '/download'
    | '/hiddify-alternative'
    | '/hysteria2-client'
    | '/migration'
    | '/mihomo-alternative'
    | '/nekobox-alternative'
    | '/privacy'
    | '/reset-password'
    | '/sing-box-gui'
    | '/sitemap-blog.xml'
    | '/sitemap-docs.xml'
    | '/terms'
    | '/v2rayn-alternative'
    | '/vless-reality-client'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/en/clash-alternative'
    | '/en/download'
    | '/en/hiddify-alternative'
    | '/en/hysteria2-client'
    | '/en/migration'
    | '/en/mihomo-alternative'
    | '/en/nekobox-alternative'
    | '/en/privacy'
    | '/en/sing-box-gui'
    | '/en/terms'
    | '/en/v2rayn-alternative'
    | '/en/vless-reality-client'
    | '/blog'
    | '/docs'
    | '/en'
    | '/api/releases/latest'
    | '/en/blog/$slug'
    | '/en/docs/$slug'
    | '/en/blog'
    | '/en/docs'
    | '/api/public/devices/resources'
    | '/api/public/devices/status'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
    | '/api/releases/download/$filename'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/clash-alternative'
    | '/devices'
    | '/docs'
    | '/download'
    | '/en'
    | '/hiddify-alternative'
    | '/hysteria2-client'
    | '/migration'
    | '/mihomo-alternative'
    | '/nekobox-alternative'
    | '/privacy'
    | '/reset-password'
    | '/sing-box-gui'
    | '/sitemap-blog.xml'
    | '/sitemap-docs.xml'
    | '/terms'
    | '/v2rayn-alternative'
    | '/vless-reality-client'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/en/blog'
    | '/en/clash-alternative'
    | '/en/docs'
    | '/en/download'
    | '/en/hiddify-alternative'
    | '/en/hysteria2-client'
    | '/en/migration'
    | '/en/mihomo-alternative'
    | '/en/nekobox-alternative'
    | '/en/privacy'
    | '/en/sing-box-gui'
    | '/en/terms'
    | '/en/v2rayn-alternative'
    | '/en/vless-reality-client'
    | '/blog/'
    | '/docs/'
    | '/en/'
    | '/api/releases/latest'
    | '/en/blog/$slug'
    | '/en/docs/$slug'
    | '/en/blog/'
    | '/en/docs/'
    | '/api/public/devices/resources'
    | '/api/public/devices/status'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
    | '/api/releases/download/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ClashAlternativeRoute: typeof ClashAlternativeRoute
  DevicesRoute: typeof DevicesRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  EnRoute: typeof EnRouteWithChildren
  HiddifyAlternativeRoute: typeof HiddifyAlternativeRoute
  Hysteria2ClientRoute: typeof Hysteria2ClientRoute
  MigrationRoute: typeof MigrationRoute
  MihomoAlternativeRoute: typeof MihomoAlternativeRoute
  NekoboxAlternativeRoute: typeof NekoboxAlternativeRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SingBoxGuiRoute: typeof SingBoxGuiRoute
  SitemapBlogDotxmlRoute: typeof SitemapBlogDotxmlRoute
  SitemapDocsDotxmlRoute: typeof SitemapDocsDotxmlRoute
  TermsRoute: typeof TermsRoute
  V2raynAlternativeRoute: typeof V2raynAlternativeRoute
  VlessRealityClientRoute: typeof VlessRealityClientRoute
  ApiReleasesLatestRoute: typeof ApiReleasesLatestRoute
  ApiPublicDevicesResourcesRoute: typeof ApiPublicDevicesResourcesRoute
  ApiPublicDevicesStatusRoute: typeof ApiPublicDevicesStatusRoute
  ApiPublicPairClaimRoute: typeof ApiPublicPairClaimRoute
  ApiPublicPairHeartbeatRoute: typeof ApiPublicPairHeartbeatRoute
  ApiReleasesDownloadFilenameRoute: typeof ApiReleasesDownloadFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clash-alternative': {
      id: '/clash-alternative'
      path: '/clash-alternative'
      fullPath: '/clash-alternative'
      preLoaderRoute: typeof ClashAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiddify-alternative': {
      id: '/hiddify-alternative'
      path: '/hiddify-alternative'
      fullPath: '/hiddify-alternative'
      preLoaderRoute: typeof HiddifyAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hysteria2-client': {
      id: '/hysteria2-client'
      path: '/hysteria2-client'
      fullPath: '/hysteria2-client'
      preLoaderRoute: typeof Hysteria2ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mihomo-alternative': {
      id: '/mihomo-alternative'
      path: '/mihomo-alternative'
      fullPath: '/mihomo-alternative'
      preLoaderRoute: typeof MihomoAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nekobox-alternative': {
      id: '/nekobox-alternative'
      path: '/nekobox-alternative'
      fullPath: '/nekobox-alternative'
      preLoaderRoute: typeof NekoboxAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sing-box-gui': {
      id: '/sing-box-gui'
      path: '/sing-box-gui'
      fullPath: '/sing-box-gui'
      preLoaderRoute: typeof SingBoxGuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blog.xml': {
      id: '/sitemap-blog.xml'
      path: '/sitemap-blog.xml'
      fullPath: '/sitemap-blog.xml'
      preLoaderRoute: typeof SitemapBlogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-docs.xml': {
      id: '/sitemap-docs.xml'
      path: '/sitemap-docs.xml'
      fullPath: '/sitemap-docs.xml'
      preLoaderRoute: typeof SitemapDocsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2rayn-alternative': {
      id: '/v2rayn-alternative'
      path: '/v2rayn-alternative'
      fullPath: '/v2rayn-alternative'
      preLoaderRoute: typeof V2raynAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vless-reality-client': {
      id: '/vless-reality-client'
      path: '/vless-reality-client'
      fullPath: '/vless-reality-client'
      preLoaderRoute: typeof VlessRealityClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/admin': {
      id: '/blog/admin'
      path: '/admin'
      fullPath: '/blog/admin'
      preLoaderRoute: typeof BlogAdminRouteImport
      parentRoute: typeof BlogRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/admin': {
      id: '/docs/admin'
      path: '/admin'
      fullPath: '/docs/admin'
      preLoaderRoute: typeof DocsAdminRouteImport
      parentRoute: typeof DocsRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/blog': {
      id: '/en/blog'
      path: '/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof EnBlogRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/clash-alternative': {
      id: '/en/clash-alternative'
      path: '/clash-alternative'
      fullPath: '/en/clash-alternative'
      preLoaderRoute: typeof EnClashAlternativeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/docs': {
      id: '/en/docs'
      path: '/docs'
      fullPath: '/en/docs'
      preLoaderRoute: typeof EnDocsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/download': {
      id: '/en/download'
      path: '/download'
      fullPath: '/en/download'
      preLoaderRoute: typeof EnDownloadRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/hiddify-alternative': {
      id: '/en/hiddify-alternative'
      path: '/hiddify-alternative'
      fullPath: '/en/hiddify-alternative'
      preLoaderRoute: typeof EnHiddifyAlternativeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/hysteria2-client': {
      id: '/en/hysteria2-client'
      path: '/hysteria2-client'
      fullPath: '/en/hysteria2-client'
      preLoaderRoute: typeof EnHysteria2ClientRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/migration': {
      id: '/en/migration'
      path: '/migration'
      fullPath: '/en/migration'
      preLoaderRoute: typeof EnMigrationRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/mihomo-alternative': {
      id: '/en/mihomo-alternative'
      path: '/mihomo-alternative'
      fullPath: '/en/mihomo-alternative'
      preLoaderRoute: typeof EnMihomoAlternativeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/nekobox-alternative': {
      id: '/en/nekobox-alternative'
      path: '/nekobox-alternative'
      fullPath: '/en/nekobox-alternative'
      preLoaderRoute: typeof EnNekoboxAlternativeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/sing-box-gui': {
      id: '/en/sing-box-gui'
      path: '/sing-box-gui'
      fullPath: '/en/sing-box-gui'
      preLoaderRoute: typeof EnSingBoxGuiRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/v2rayn-alternative': {
      id: '/en/v2rayn-alternative'
      path: '/v2rayn-alternative'
      fullPath: '/en/v2rayn-alternative'
      preLoaderRoute: typeof EnV2raynAlternativeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/vless-reality-client': {
      id: '/en/vless-reality-client'
      path: '/vless-reality-client'
      fullPath: '/en/vless-reality-client'
      preLoaderRoute: typeof EnVlessRealityClientRouteImport
      parentRoute: typeof EnRoute
    }
    '/api/releases/latest': {
      id: '/api/releases/latest'
      path: '/api/releases/latest'
      fullPath: '/api/releases/latest'
      preLoaderRoute: typeof ApiReleasesLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/': {
      id: '/en/blog/'
      path: '/'
      fullPath: '/en/blog/'
      preLoaderRoute: typeof EnBlogIndexRouteImport
      parentRoute: typeof EnBlogRoute
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof EnBlogRoute
    }
    '/en/docs/': {
      id: '/en/docs/'
      path: '/'
      fullPath: '/en/docs/'
      preLoaderRoute: typeof EnDocsIndexRouteImport
      parentRoute: typeof EnDocsRoute
    }
    '/en/docs/$slug': {
      id: '/en/docs/$slug'
      path: '/$slug'
      fullPath: '/en/docs/$slug'
      preLoaderRoute: typeof EnDocsSlugRouteImport
      parentRoute: typeof EnDocsRoute
    }
    '/api/public/devices/resources': {
      id: '/api/public/devices/resources'
      path: '/api/public/devices/resources'
      fullPath: '/api/public/devices/resources'
      preLoaderRoute: typeof ApiPublicDevicesResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/status': {
      id: '/api/public/devices/status'
      path: '/api/public/devices/status'
      fullPath: '/api/public/devices/status'
      preLoaderRoute: typeof ApiPublicDevicesStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair/claim': {
      id: '/api/public/pair/claim'
      path: '/api/public/pair/claim'
      fullPath: '/api/public/pair/claim'
      preLoaderRoute: typeof ApiPublicPairClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair/heartbeat': {
      id: '/api/public/pair/heartbeat'
      path: '/api/public/pair/heartbeat'
      fullPath: '/api/public/pair/heartbeat'
      preLoaderRoute: typeof ApiPublicPairHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/releases/download/$filename': {
      id: '/api/releases/download/$filename'
      path: '/api/releases/download/$filename'
      fullPath: '/api/releases/download/$filename'
      preLoaderRoute: typeof ApiReleasesDownloadFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAdminRoute: typeof BlogAdminRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogAdminRoute: BlogAdminRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsAdminRoute: typeof DocsAdminRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsAdminRoute: DocsAdminRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface EnBlogRouteChildren {
  EnBlogSlugRoute: typeof EnBlogSlugRoute
  EnBlogIndexRoute: typeof EnBlogIndexRoute
}

const EnBlogRouteChildren: EnBlogRouteChildren = {
  EnBlogSlugRoute: EnBlogSlugRoute,
  EnBlogIndexRoute: EnBlogIndexRoute,
}

const EnBlogRouteWithChildren =
  EnBlogRoute._addFileChildren(EnBlogRouteChildren)

interface EnDocsRouteChildren {
  EnDocsSlugRoute: typeof EnDocsSlugRoute
  EnDocsIndexRoute: typeof EnDocsIndexRoute
}

const EnDocsRouteChildren: EnDocsRouteChildren = {
  EnDocsSlugRoute: EnDocsSlugRoute,
  EnDocsIndexRoute: EnDocsIndexRoute,
}

const EnDocsRouteWithChildren =
  EnDocsRoute._addFileChildren(EnDocsRouteChildren)

interface EnRouteChildren {
  EnBlogRoute: typeof EnBlogRouteWithChildren
  EnClashAlternativeRoute: typeof EnClashAlternativeRoute
  EnDocsRoute: typeof EnDocsRouteWithChildren
  EnDownloadRoute: typeof EnDownloadRoute
  EnHiddifyAlternativeRoute: typeof EnHiddifyAlternativeRoute
  EnHysteria2ClientRoute: typeof EnHysteria2ClientRoute
  EnMigrationRoute: typeof EnMigrationRoute
  EnMihomoAlternativeRoute: typeof EnMihomoAlternativeRoute
  EnNekoboxAlternativeRoute: typeof EnNekoboxAlternativeRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnSingBoxGuiRoute: typeof EnSingBoxGuiRoute
  EnTermsRoute: typeof EnTermsRoute
  EnV2raynAlternativeRoute: typeof EnV2raynAlternativeRoute
  EnVlessRealityClientRoute: typeof EnVlessRealityClientRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnBlogRoute: EnBlogRouteWithChildren,
  EnClashAlternativeRoute: EnClashAlternativeRoute,
  EnDocsRoute: EnDocsRouteWithChildren,
  EnDownloadRoute: EnDownloadRoute,
  EnHiddifyAlternativeRoute: EnHiddifyAlternativeRoute,
  EnHysteria2ClientRoute: EnHysteria2ClientRoute,
  EnMigrationRoute: EnMigrationRoute,
  EnMihomoAlternativeRoute: EnMihomoAlternativeRoute,
  EnNekoboxAlternativeRoute: EnNekoboxAlternativeRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnSingBoxGuiRoute: EnSingBoxGuiRoute,
  EnTermsRoute: EnTermsRoute,
  EnV2raynAlternativeRoute: EnV2raynAlternativeRoute,
  EnVlessRealityClientRoute: EnVlessRealityClientRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ClashAlternativeRoute: ClashAlternativeRoute,
  DevicesRoute: DevicesRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  EnRoute: EnRouteWithChildren,
  HiddifyAlternativeRoute: HiddifyAlternativeRoute,
  Hysteria2ClientRoute: Hysteria2ClientRoute,
  MigrationRoute: MigrationRoute,
  MihomoAlternativeRoute: MihomoAlternativeRoute,
  NekoboxAlternativeRoute: NekoboxAlternativeRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SingBoxGuiRoute: SingBoxGuiRoute,
  SitemapBlogDotxmlRoute: SitemapBlogDotxmlRoute,
  SitemapDocsDotxmlRoute: SitemapDocsDotxmlRoute,
  TermsRoute: TermsRoute,
  V2raynAlternativeRoute: V2raynAlternativeRoute,
  VlessRealityClientRoute: VlessRealityClientRoute,
  ApiReleasesLatestRoute: ApiReleasesLatestRoute,
  ApiPublicDevicesResourcesRoute: ApiPublicDevicesResourcesRoute,
  ApiPublicDevicesStatusRoute: ApiPublicDevicesStatusRoute,
  ApiPublicPairClaimRoute: ApiPublicPairClaimRoute,
  ApiPublicPairHeartbeatRoute: ApiPublicPairHeartbeatRoute,
  ApiReleasesDownloadFilenameRoute: ApiReleasesDownloadFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
