/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogAdminRouteImport } from './routes/blog.admin'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DocsAdminRouteImport } from './routes/docs.admin'
import { Route as ApiPublicPairClaimRouteImport } from './routes/api/public/pair/claim'
import { Route as ApiPublicPairHeartbeatRouteImport } from './routes/api/public/pair/heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAdminRoute = BlogAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BlogRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAdminRoute = DocsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DocsRoute,
} as any)
const ApiPublicPairClaimRoute = ApiPublicPairClaimRouteImport.update({
  id: '/api/public/pair/claim',
  path: '/api/public/pair/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairHeartbeatRoute = ApiPublicPairHeartbeatRouteImport.update({
  id: '/api/public/pair/heartbeat',
  path: '/api/public/pair/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/migration': typeof MigrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/devices': typeof DevicesRoute
  '/download': typeof DownloadRoute
  '/migration': typeof MigrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/migration': typeof MigrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/devices'
    | '/docs'
    | '/download'
    | '/migration'
    | '/reset-password'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/blog/'
    | '/docs/'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/devices'
    | '/download'
    | '/migration'
    | '/reset-password'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/blog'
    | '/docs'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/devices'
    | '/docs'
    | '/download'
    | '/migration'
    | '/reset-password'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/blog/'
    | '/docs/'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  DevicesRoute: typeof DevicesRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  MigrationRoute: typeof MigrationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPairClaimRoute: typeof ApiPublicPairClaimRoute
  ApiPublicPairHeartbeatRoute: typeof ApiPublicPairHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/admin': {
      id: '/blog/admin'
      path: '/admin'
      fullPath: '/blog/admin'
      preLoaderRoute: typeof BlogAdminRouteImport
      parentRoute: typeof BlogRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/admin': {
      id: '/docs/admin'
      path: '/admin'
      fullPath: '/docs/admin'
      preLoaderRoute: typeof DocsAdminRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/public/pair/claim': {
      id: '/api/public/pair/claim'
      path: '/api/public/pair/claim'
      fullPath: '/api/public/pair/claim'
      preLoaderRoute: typeof ApiPublicPairClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair/heartbeat': {
      id: '/api/public/pair/heartbeat'
      path: '/api/public/pair/heartbeat'
      fullPath: '/api/public/pair/heartbeat'
      preLoaderRoute: typeof ApiPublicPairHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAdminRoute: typeof BlogAdminRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogAdminRoute: BlogAdminRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsAdminRoute: typeof DocsAdminRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsAdminRoute: DocsAdminRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  DevicesRoute: DevicesRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  MigrationRoute: MigrationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPairClaimRoute: ApiPublicPairClaimRoute,
  ApiPublicPairHeartbeatRoute: ApiPublicPairHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
