/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ClashAlternativeRouteImport } from './routes/clash-alternative'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EnRouteImport } from './routes/en'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as MihomoAlternativeRouteImport } from './routes/mihomo-alternative'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogAdminRouteImport } from './routes/blog.admin'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DocsAdminRouteImport } from './routes/docs.admin'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnBlogRouteImport } from './routes/en.blog'
import { Route as EnClashAlternativeRouteImport } from './routes/en.clash-alternative'
import { Route as EnDocsRouteImport } from './routes/en.docs'
import { Route as EnDownloadRouteImport } from './routes/en.download'
import { Route as EnMigrationRouteImport } from './routes/en.migration'
import { Route as EnMihomoAlternativeRouteImport } from './routes/en.mihomo-alternative'
import { Route as EnBlogIndexRouteImport } from './routes/en.blog.index'
import { Route as EnBlogSlugRouteImport } from './routes/en.blog.$slug'
import { Route as EnDocsIndexRouteImport } from './routes/en.docs.index'
import { Route as EnDocsSlugRouteImport } from './routes/en.docs.$slug'
import { Route as ApiPublicPairClaimRouteImport } from './routes/api/public/pair/claim'
import { Route as ApiPublicPairHeartbeatRouteImport } from './routes/api/public/pair/heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClashAlternativeRoute = ClashAlternativeRouteImport.update({
  id: '/clash-alternative',
  path: '/clash-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const MihomoAlternativeRoute = MihomoAlternativeRouteImport.update({
  id: '/mihomo-alternative',
  path: '/mihomo-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAdminRoute = BlogAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BlogRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAdminRoute = DocsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DocsRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnBlogRoute = EnBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => EnRoute,
} as any)
const EnClashAlternativeRoute = EnClashAlternativeRouteImport.update({
  id: '/clash-alternative',
  path: '/clash-alternative',
  getParentRoute: () => EnRoute,
} as any)
const EnDocsRoute = EnDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => EnRoute,
} as any)
const EnDownloadRoute = EnDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => EnRoute,
} as any)
const EnMigrationRoute = EnMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => EnRoute,
} as any)
const EnMihomoAlternativeRoute = EnMihomoAlternativeRouteImport.update({
  id: '/mihomo-alternative',
  path: '/mihomo-alternative',
  getParentRoute: () => EnRoute,
} as any)
const EnBlogIndexRoute = EnBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnBlogRoute,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnBlogRoute,
} as any)
const EnDocsIndexRoute = EnDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnDocsRoute,
} as any)
const EnDocsSlugRoute = EnDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnDocsRoute,
} as any)
const ApiPublicPairClaimRoute = ApiPublicPairClaimRouteImport.update({
  id: '/api/public/pair/claim',
  path: '/api/public/pair/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairHeartbeatRoute = ApiPublicPairHeartbeatRouteImport.update({
  id: '/api/public/pair/heartbeat',
  path: '/api/public/pair/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/clash-alternative': typeof ClashAlternativeRoute
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/en': typeof EnRouteWithChildren
  '/migration': typeof MigrationRoute
  '/mihomo-alternative': typeof MihomoAlternativeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/clash-alternative': typeof EnClashAlternativeRoute
  '/en/docs': typeof EnDocsRouteWithChildren
  '/en/download': typeof EnDownloadRoute
  '/en/migration': typeof EnMigrationRoute
  '/en/mihomo-alternative': typeof EnMihomoAlternativeRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
  '/en/docs/': typeof EnDocsIndexRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/clash-alternative': typeof ClashAlternativeRoute
  '/devices': typeof DevicesRoute
  '/download': typeof DownloadRoute
  '/migration': typeof MigrationRoute
  '/mihomo-alternative': typeof MihomoAlternativeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/en/clash-alternative': typeof EnClashAlternativeRoute
  '/en/download': typeof EnDownloadRoute
  '/en/migration': typeof EnMigrationRoute
  '/en/mihomo-alternative': typeof EnMihomoAlternativeRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/en': typeof EnIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/blog': typeof EnBlogIndexRoute
  '/en/docs': typeof EnDocsIndexRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/clash-alternative': typeof ClashAlternativeRoute
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/en': typeof EnRouteWithChildren
  '/migration': typeof MigrationRoute
  '/mihomo-alternative': typeof MihomoAlternativeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/admin': typeof DocsAdminRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/clash-alternative': typeof EnClashAlternativeRoute
  '/en/docs': typeof EnDocsRouteWithChildren
  '/en/download': typeof EnDownloadRoute
  '/en/migration': typeof EnMigrationRoute
  '/en/mihomo-alternative': typeof EnMihomoAlternativeRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
  '/en/docs/': typeof EnDocsIndexRoute
  '/api/public/pair/claim': typeof ApiPublicPairClaimRoute
  '/api/public/pair/heartbeat': typeof ApiPublicPairHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/clash-alternative'
    | '/devices'
    | '/docs'
    | '/download'
    | '/en'
    | '/migration'
    | '/mihomo-alternative'
    | '/reset-password'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/en/blog'
    | '/en/clash-alternative'
    | '/en/docs'
    | '/en/download'
    | '/en/migration'
    | '/en/mihomo-alternative'
    | '/blog/'
    | '/docs/'
    | '/en/'
    | '/en/blog/$slug'
    | '/en/docs/$slug'
    | '/en/blog/'
    | '/en/docs/'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/clash-alternative'
    | '/devices'
    | '/download'
    | '/migration'
    | '/mihomo-alternative'
    | '/reset-password'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/en/clash-alternative'
    | '/en/download'
    | '/en/migration'
    | '/en/mihomo-alternative'
    | '/blog'
    | '/docs'
    | '/en'
    | '/en/blog/$slug'
    | '/en/docs/$slug'
    | '/en/blog'
    | '/en/docs'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/clash-alternative'
    | '/devices'
    | '/docs'
    | '/download'
    | '/en'
    | '/migration'
    | '/mihomo-alternative'
    | '/reset-password'
    | '/blog/$slug'
    | '/blog/admin'
    | '/docs/$slug'
    | '/docs/admin'
    | '/en/blog'
    | '/en/clash-alternative'
    | '/en/docs'
    | '/en/download'
    | '/en/migration'
    | '/en/mihomo-alternative'
    | '/blog/'
    | '/docs/'
    | '/en/'
    | '/en/blog/$slug'
    | '/en/docs/$slug'
    | '/en/blog/'
    | '/en/docs/'
    | '/api/public/pair/claim'
    | '/api/public/pair/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ClashAlternativeRoute: typeof ClashAlternativeRoute
  DevicesRoute: typeof DevicesRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  EnRoute: typeof EnRouteWithChildren
  MigrationRoute: typeof MigrationRoute
  MihomoAlternativeRoute: typeof MihomoAlternativeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPairClaimRoute: typeof ApiPublicPairClaimRoute
  ApiPublicPairHeartbeatRoute: typeof ApiPublicPairHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clash-alternative': {
      id: '/clash-alternative'
      path: '/clash-alternative'
      fullPath: '/clash-alternative'
      preLoaderRoute: typeof ClashAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mihomo-alternative': {
      id: '/mihomo-alternative'
      path: '/mihomo-alternative'
      fullPath: '/mihomo-alternative'
      preLoaderRoute: typeof MihomoAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/admin': {
      id: '/blog/admin'
      path: '/admin'
      fullPath: '/blog/admin'
      preLoaderRoute: typeof BlogAdminRouteImport
      parentRoute: typeof BlogRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/admin': {
      id: '/docs/admin'
      path: '/admin'
      fullPath: '/docs/admin'
      preLoaderRoute: typeof DocsAdminRouteImport
      parentRoute: typeof DocsRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/blog': {
      id: '/en/blog'
      path: '/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof EnBlogRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/clash-alternative': {
      id: '/en/clash-alternative'
      path: '/clash-alternative'
      fullPath: '/en/clash-alternative'
      preLoaderRoute: typeof EnClashAlternativeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/docs': {
      id: '/en/docs'
      path: '/docs'
      fullPath: '/en/docs'
      preLoaderRoute: typeof EnDocsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/download': {
      id: '/en/download'
      path: '/download'
      fullPath: '/en/download'
      preLoaderRoute: typeof EnDownloadRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/migration': {
      id: '/en/migration'
      path: '/migration'
      fullPath: '/en/migration'
      preLoaderRoute: typeof EnMigrationRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/mihomo-alternative': {
      id: '/en/mihomo-alternative'
      path: '/mihomo-alternative'
      fullPath: '/en/mihomo-alternative'
      preLoaderRoute: typeof EnMihomoAlternativeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/blog/': {
      id: '/en/blog/'
      path: '/'
      fullPath: '/en/blog/'
      preLoaderRoute: typeof EnBlogIndexRouteImport
      parentRoute: typeof EnBlogRoute
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof EnBlogRoute
    }
    '/en/docs/': {
      id: '/en/docs/'
      path: '/'
      fullPath: '/en/docs/'
      preLoaderRoute: typeof EnDocsIndexRouteImport
      parentRoute: typeof EnDocsRoute
    }
    '/en/docs/$slug': {
      id: '/en/docs/$slug'
      path: '/$slug'
      fullPath: '/en/docs/$slug'
      preLoaderRoute: typeof EnDocsSlugRouteImport
      parentRoute: typeof EnDocsRoute
    }
    '/api/public/pair/claim': {
      id: '/api/public/pair/claim'
      path: '/api/public/pair/claim'
      fullPath: '/api/public/pair/claim'
      preLoaderRoute: typeof ApiPublicPairClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair/heartbeat': {
      id: '/api/public/pair/heartbeat'
      path: '/api/public/pair/heartbeat'
      fullPath: '/api/public/pair/heartbeat'
      preLoaderRoute: typeof ApiPublicPairHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAdminRoute: typeof BlogAdminRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogAdminRoute: BlogAdminRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsAdminRoute: typeof DocsAdminRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsAdminRoute: DocsAdminRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface EnBlogRouteChildren {
  EnBlogSlugRoute: typeof EnBlogSlugRoute
  EnBlogIndexRoute: typeof EnBlogIndexRoute
}

const EnBlogRouteChildren: EnBlogRouteChildren = {
  EnBlogSlugRoute: EnBlogSlugRoute,
  EnBlogIndexRoute: EnBlogIndexRoute,
}

const EnBlogRouteWithChildren =
  EnBlogRoute._addFileChildren(EnBlogRouteChildren)

interface EnDocsRouteChildren {
  EnDocsSlugRoute: typeof EnDocsSlugRoute
  EnDocsIndexRoute: typeof EnDocsIndexRoute
}

const EnDocsRouteChildren: EnDocsRouteChildren = {
  EnDocsSlugRoute: EnDocsSlugRoute,
  EnDocsIndexRoute: EnDocsIndexRoute,
}

const EnDocsRouteWithChildren =
  EnDocsRoute._addFileChildren(EnDocsRouteChildren)

interface EnRouteChildren {
  EnBlogRoute: typeof EnBlogRouteWithChildren
  EnClashAlternativeRoute: typeof EnClashAlternativeRoute
  EnDocsRoute: typeof EnDocsRouteWithChildren
  EnDownloadRoute: typeof EnDownloadRoute
  EnMigrationRoute: typeof EnMigrationRoute
  EnMihomoAlternativeRoute: typeof EnMihomoAlternativeRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnBlogRoute: EnBlogRouteWithChildren,
  EnClashAlternativeRoute: EnClashAlternativeRoute,
  EnDocsRoute: EnDocsRouteWithChildren,
  EnDownloadRoute: EnDownloadRoute,
  EnMigrationRoute: EnMigrationRoute,
  EnMihomoAlternativeRoute: EnMihomoAlternativeRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ClashAlternativeRoute: ClashAlternativeRoute,
  DevicesRoute: DevicesRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  EnRoute: EnRouteWithChildren,
  MigrationRoute: MigrationRoute,
  MihomoAlternativeRoute: MihomoAlternativeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPairClaimRoute: ApiPublicPairClaimRoute,
  ApiPublicPairHeartbeatRoute: ApiPublicPairHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
